"""Curated additions: high-value Swiss key accounts and EVUs missing from the
2025-12 base list. Sources: VSE Verteilnetzbetreiber-Verzeichnis (strom.ch),
Handelszeitung Top 500, Statista Best Employers 2026, public hospital rankings,
World's Best Hospitals 2026.

Row format (tuple, matching HEADERS in build_crm.py):
  (Prio, Segment, Firma, Ort, PLZ, Kanton, Ansprechpartner, Funktion,
   E-Mail, Telefon, Website, Nächster Schritt, Bedarf, Hauptprodukt, Notizen, Internes)
"""

# Each tuple: (prio, segment, firma, ort, plz, kanton, ansprech, funktion,
#              email, tel, website, naechster_schritt, bedarf, hauptprodukt, notizen, internes)

ADDITIONAL_ACCOUNTS = [
    # ============ EVU / Netzbetreiber (Stadtwerke + Verteilnetzbetreiber) ============
    ("A", "EVU/Netzbetreiber", "Primeo Energie", "Münchenstein", "4142", "BL",
     "Leiter Netzbetrieb", "Dipl. El.-Ing.", "info@primeo-energie.ch",
     "+41 61 415 41 41", "https://www.primeo-energie.ch",
     "Stromversorger NWCH; PQ-Analyse + BESS-Pitch", "Netzbetrieb NWCH; 230k Kunden; PQ", "BESS",
     "Adr: Weidenstrasse 27, 4142 Münchenstein | Strom + Wärme NWCH", "EVU NWCH"),
    ("A", "EVU/Netzbetreiber", "naturenergie AG (EBL/EBM)", "Rheinfelden", "4310", "AG",
     "Leiter Verteilnetz", "Dipl. El.-Ing.", "info@naturenergie.ch",
     "+41 61 833 41 41", "https://www.naturenergie.ch",
     "Joint Venture EBL/EBM; mobile MS-Verteilung", "Verteilnetz AG/BL; Stage-V-Generatoren", "Generator",
     "Adr: Schlossweg 10, 4310 Rheinfelden | Wasserkraft + Verteilnetz", "EVU Aargau"),
    ("A", "EVU/Netzbetreiber", "St.Galler Stadtwerke (sgsw)", "St. Gallen", "9000", "SG",
     "Leiter Netzbetrieb", "Dipl. El.-Ing.", "info@sgsw.ch",
     "+41 71 224 55 55", "https://www.sgsw.ch",
     "Stadtwerk SG; TSO-DSO Coordination Partner", "MS-Verteilung; BESS; Revisionen", "BESS",
     "Adr: St. Leonhard-Strasse 15, 9000 St. Gallen", "Stadtwerk SG"),
    ("A", "EVU/Netzbetreiber", "ewl Energie Wasser Luzern", "Luzern", "6002", "LU",
     "Leiter Energienetze", "Dipl. El.-Ing.", "info@ewl-luzern.ch",
     "+41 41 369 41 11", "https://www.ewl-luzern.ch",
     "Stadtwerk Luzern; FW + Strom + Wasser", "Mobile MS-Verteilung; Tunnel-Revision", "Mobile MS-Verteilung",
     "Adr: Industriestrasse 6, 6002 Luzern", "Stadtwerk LU"),
    ("A", "EVU/Netzbetreiber", "IBAarau (Industrielle Betriebe Aarau)", "Aarau", "5000", "AG",
     "Leiter Verteilnetz", "Dipl. El.-Ing.", "info@ibaarau.ch",
     "+41 62 835 02 30", "https://www.ibaarau.ch",
     "Stadtwerk Aarau; PQ + Notstrom Stadtmitte", "MS-Verteilung Innenstadt", "Generator",
     "Adr: Obere Vorstadt 37, 5000 Aarau", "Stadtwerk AG"),
    ("A", "EVU/Netzbetreiber", "IBC Energie Wasser Chur", "Chur", "7000", "GR",
     "Leiter Netz", "Dipl. El.-Ing.", "info@ibc-chur.ch",
     "+41 81 254 47 47", "https://www.ibc-chur.ch",
     "Stadtwerk Chur; alpine Versorgung", "BESS für Hochgebirge; Generator Revision", "BESS",
     "Adr: Felsenaustrasse 29, 7000 Chur", "Stadtwerk GR"),
    ("B", "EVU/Netzbetreiber", "Energie Thun AG", "Thun", "3601", "BE",
     "Leiter Netzbetrieb", "Dipl. El.-Ing.", "info@energiethun.ch",
     "+41 33 225 22 22", "https://www.energiethun.ch",
     "Regionalversorger Thun-Oberland", "Mobile Versorgung Tourismus", "Generator",
     "Adr: Industriestrasse 6, 3603 Thun", "Stadtwerk BE"),
    ("B", "EVU/Netzbetreiber", "Regionalwerke AG Baden", "Baden", "5400", "AG",
     "Leiter Verteilnetz", "Dipl. El.-Ing.", "info@regionalwerke.ch",
     "+41 56 200 22 22", "https://www.regionalwerke.ch",
     "VNB Baden + Umgebung", "Mobile MS-Verteilung", "Mobile MS-Verteilung",
     "Adr: Haselstrasse 15, 5400 Baden", "VNB AG"),
    ("B", "EVU/Netzbetreiber", "Localnet AG Burgdorf", "Burgdorf", "3401", "BE",
     "Leiter Netzbetrieb", "Dipl. El.-Ing.", "info@localnet.ch",
     "+41 34 420 00 00", "https://www.localnet.ch",
     "Stadtnetz Burgdorf; Industriegebiet", "Notstrom Industriequartier", "Generator",
     "Adr: Bernstrasse 7, 3401 Burgdorf", "Stadtwerk BE"),
    ("B", "EVU/Netzbetreiber", "ewa-energieuri AG", "Altdorf", "6460", "UR",
     "Leiter Netz", "Dipl. El.-Ing.", "info@ewa.ch",
     "+41 41 875 75 75", "https://www.ewa.ch",
     "Kantonsversorger UR; Wasserkraft", "BESS für Alpinregion", "BESS",
     "Adr: Herrengasse 1, 6460 Altdorf", "Kantonswerk UR"),
    ("B", "EVU/Netzbetreiber", "Werke am Zürichsee AG (WAZ)", "Stäfa", "8712", "ZH",
     "Leiter Netz", "Dipl. El.-Ing.", "info@waz.ch",
     "+41 44 928 90 00", "https://www.waz.ch",
     "Versorger rechtes Zürichseeufer", "Mobile MS für Bauprojekte", "Mobile MS-Verteilung",
     "Adr: Seestrasse 100, 8712 Stäfa", "Stadtwerk ZH"),
    ("B", "EVU/Netzbetreiber", "EWO Elektrizitätswerk Obwalden", "Kerns", "6064", "OW",
     "Leiter Netz", "Dipl. El.-Ing.", "info@ewo.ch",
     "+41 41 666 41 41", "https://www.ewo.ch",
     "Kantonswerk OW", "Notstrom Bergregion", "Generator",
     "Adr: Sand 7, 6064 Kerns", "Kantonswerk OW"),
    ("B", "EVU/Netzbetreiber", "EW Nidwalden (EWN)", "Stans", "6371", "NW",
     "Leiter Netz", "Dipl. El.-Ing.", "info@ew-nidwalden.ch",
     "+41 41 618 70 00", "https://www.ew-nidwalden.ch",
     "Kantonswerk NW", "BESS + Generator", "Generator",
     "Adr: Buochserstrasse 1, 6371 Stans", "Kantonswerk NW"),
    ("B", "EVU/Netzbetreiber", "ewd Elektrizitätswerk Davos", "Davos Platz", "7270", "GR",
     "Leiter Netz", "Dipl. El.-Ing.", "info@ewd.ch",
     "+41 81 415 71 71", "https://www.ewd.ch",
     "WEF Davos; mobile Notstrom Hotspots", "Eventversorgung WEF; BESS", "BESS + Generator",
     "Adr: Promenade 49, 7270 Davos Platz", "Bergregion"),
    ("B", "EVU/Netzbetreiber", "Energie Service Biel/Bienne (ESB)", "Biel/Bienne", "2502", "BE",
     "Leiter Netz", "Dipl. El.-Ing.", "info@esb.ch",
     "+41 32 321 12 11", "https://www.esb.ch",
     "Stadtwerk Biel; Uhrenindustrie", "PQ für Uhrenproduktion", "PQ-Analyse",
     "Adr: Gottstattstrasse 4, 2502 Biel", "Stadtwerk BE"),
    ("A", "EVU/Netzbetreiber", "BKW Energie AG (Konzernzentrale)", "Bern", "3013", "BE",
     "Leiter Netzbetrieb CH", "Dipl. El.-Ing.", "info@bkw.ch",
     "+41 58 477 51 11", "https://www.bkw.ch",
     "Grossversorger BE/SO/FR/JU; Aggreko-Synergien", "Übertragungs- + Verteilnetz; BESS Pilotanlage", "BESS + Generator",
     "Adr: Viktoriaplatz 2, 3013 Bern | Börse SIX:BKW", "Top-EVU"),

    # ============ Pharma / Chemie (zusätzliche Werke + Hauptsitze) ============
    ("A", "Pharma/Chemie", "Givaudan Schweiz AG (Vernier)", "Vernier", "1214", "GE",
     "Director Operations", "MSc Process Eng.", "info.switzerland@givaudan.com",
     "+41 22 780 91 11", "https://www.givaudan.com",
     "Riechstoff/Aroma; GMP-Reinraum NEA", "Aromaproduktion GE; NEA 2 MVA; ISO 50001", "USV",
     "Adr: Chemin de la Parfumerie 5, 1214 Vernier | Weltmarktführer Aromen", "Aromen Weltmarktführer"),
    ("A", "Pharma/Chemie", "Bachem AG (Bubendorf)", "Bubendorf", "4416", "BL",
     "Leiter Engineering", "Dipl. El.-Ing.", "info@bachem.com",
     "+41 61 935 23 23", "https://www.bachem.com",
     "Peptidsynthese; GMP-Notstrom", "USV Reinräume; NEA 3 MVA Stage V", "USV",
     "Adr: Hauptstrasse 144, 4416 Bubendorf | Top-3 weltweit Peptide", "Peptid-Spezialist"),
    ("A", "Pharma/Chemie", "Vifor Pharma (CSL Vifor)", "St. Gallen", "9014", "SG",
     "Director Engineering", "MSc Chem.-Ing.", "info@viforpharma.com",
     "+41 58 851 80 00", "https://www.viforpharma.com",
     "Iron deficiency therapy; GMP NEA", "Pharma GMP; NEA 4 MVA", "Generator",
     "Adr: Rechenstrasse 37, 9014 St. Gallen | Nephrologie Marktführer", "CSL-Tochter"),
    ("A", "Pharma/Chemie", "Ypsomed AG (Burgdorf)", "Burgdorf", "3401", "BE",
     "Leiter Werksinstandhaltung", "Dipl. El.-Ing.", "info@ypsomed.com",
     "+41 34 424 41 11", "https://www.ypsomed.com",
     "Injektionssysteme; Reinraum-Notstrom", "USV Reinraum Klasse C/D", "USV",
     "Adr: Brunnmattstrasse 6, 3401 Burgdorf | Marktführer Pens", "Medtech"),
    ("A", "Pharma/Chemie", "Galenica AG (Bern HQ)", "Bern", "3001", "BE",
     "Director Real Estate", "MBA", "info@galenica.com",
     "+41 58 852 81 11", "https://www.galenica.com",
     "Logistik + Apothekenkette; Notstrom Lager", "NEA Logistikzentrum; USV IT", "Generator",
     "Adr: Untermattweg 8, 3001 Bern | Apotheke + Vertrieb", "Pharma-Vertrieb"),
    ("A", "Pharma/Chemie", "Roche Diagnostics (Rotkreuz HQ)", "Rotkreuz", "6343", "ZG",
     "Director Site Engineering", "MSc El.-Ing.", "info@roche.com",
     "+41 41 798 71 11", "https://www.roche.com",
     "Diagnostics R&D + Produktion ZG", "GMP NEA 6 MVA; USV Reinräume; ISO 50001", "BESS + Generator",
     "Adr: Forrenstrasse 2, 6343 Rotkreuz | 4'500 MA Standort", "Roche-Diagnostics"),

    # ============ Rechenzentrum / IT / Telekom ============
    ("A", "Rechenzentrum/IT", "Green Datacenter AG", "Lupfig", "5242", "AG",
     "Director Operations", "MSc El.-Ing.", "info@green.ch",
     "+41 56 460 23 23", "https://www.green.ch/datacenter",
     "Grösstes Privat-RZ CH; Metro Campus", "BESS + Generator 20 MVA; PQ Kl.A", "BESS + Generator",
     "Adr: Industriestrasse 8, 5242 Lupfig | Tier IV + 28 MW", "Top-Tier-RZ"),
    ("A", "Rechenzentrum/IT", "Safe Host SA (Gland)", "Gland", "1196", "VD",
     "Director Operations", "MSc El.-Ing.", "info@safehost.com",
     "+41 22 363 12 12", "https://www.safehost.com",
     "Carrier-neutral colocation VD", "USV + BESS; 24/7 Notstrom", "USV",
     "Adr: Avenue Mont-Blanc 33, 1196 Gland | Tier III+", "Colocation VD"),
    ("A", "Rechenzentrum/IT", "Interxion Switzerland (Zürich)", "Glattbrugg", "8152", "ZH",
     "Site Director", "MSc El.-Ing.", "info@interxion.com",
     "+41 44 866 25 00", "https://www.interxion.com/locations/zurich",
     "Digital Realty Carrier Hotel ZH", "BESS + Generator 15 MVA", "BESS + Generator",
     "Adr: Hofwiesenstrasse 350, 8152 Glattbrugg", "Carrier-Hotel"),
    ("A", "Rechenzentrum/IT", "e-shelter Datacenter (NTT)", "Rümlang", "8153", "ZH",
     "Director Critical Facilities", "MSc El.-Ing.", "info@ntt.com",
     "+41 44 818 47 47", "https://services.global.ntt",
     "Hyperscale RZ ZH-North", "USV + BESS; Backup-Generatoren 10 MVA", "USV",
     "Adr: Riedmattstrasse, 8153 Rümlang", "NTT-Tochter"),
    ("A", "Rechenzentrum/IT", "Salt Mobile SA (HQ)", "Renens", "1020", "VD",
     "Director Network", "MSc El.-Ing.", "info@salt.ch",
     "+41 22 365 13 13", "https://www.salt.ch",
     "Mobilfunkbetreiber #3 CH; RAN-Notstrom", "USV + Generator Mobilfunkstandorte", "USV",
     "Adr: Rue du Caudray 4, 1020 Renens", "Telco"),
    ("A", "Rechenzentrum/IT", "Init7 (Schweiz) AG", "Winterthur", "8404", "ZH",
     "CTO", "Dipl. El.-Ing.", "info@init7.net",
     "+41 44 315 44 00", "https://www.init7.net",
     "Carrier-neutral ISP; FTTH-Pionier", "USV + Generator Kollokation", "USV",
     "Adr: Technoparkstrasse 5, 8404 Winterthur", "Independent ISP"),
    ("B", "Rechenzentrum/IT", "Quickline AG", "Nidau", "2560", "BE",
     "Leiter Netzbetrieb", "Dipl. El.-Ing.", "info@quickline.ch",
     "+41 800 84 10 20", "https://www.quickline.ch",
     "Kabelnetz-Verbund Schweiz", "Notstrom Kopfstationen", "Generator",
     "Adr: Aarbergstrasse 95, 2560 Nidau", "Kabelnetz"),

    # ============ Industrie / Maschinenbau ============
    ("A", "Industrie/Maschinenbau", "Liebherr-International AG (Bulle)", "Bulle", "1630", "FR",
     "Leiter Werksinstandhaltung", "MSc El.-Ing.", "info.lib@liebherr.com",
     "+41 26 913 31 11", "https://www.liebherr.com",
     "Industriekräne; Produktion Stage V", "Generator Stage V; PQ Kl.A", "Generator",
     "Adr: Rue de l'Industrie 45, 1630 Bulle | 1'200 MA", "Bau-Engineering"),
    ("A", "Industrie/Maschinenbau", "Schurter AG", "Luzern", "6002", "LU",
     "Director Operations", "Dipl. El.-Ing.", "contact@schurter.com",
     "+41 41 369 31 11", "https://www.schurter.com",
     "Elektromechanik; Werkenergie LU", "PQ-Analyse Produktion; USV", "PQ-Analyse",
     "Adr: Werkhofstrasse 8-12, 6002 Luzern", "Elektromechanik"),
    ("A", "Industrie/Maschinenbau", "VAT Group AG", "Haag", "9469", "SG",
     "Director Facilities", "MSc Engineering", "info@vatvalve.com",
     "+41 81 771 61 61", "https://www.vatvalve.com",
     "Vakuumventile (Halbleiter)", "PQ Kl.A; USV Reinraum", "PQ-Analyse",
     "Adr: Seelistrasse 1, 9469 Haag | Marktführer Vakuumventile", "Semiconductor"),
    ("A", "Industrie/Maschinenbau", "Comet Group", "Flamatt", "3175", "FR",
     "Director Site Engineering", "Dipl. El.-Ing.", "info@comet.tech",
     "+41 31 744 90 00", "https://www.comet.tech",
     "Plasma + Röntgentechnologie", "USV + PQ-Monitoring", "USV",
     "Adr: Herrengasse 10, 3175 Flamatt", "Plasma + RX"),
    ("A", "Industrie/Maschinenbau", "u-blox AG", "Thalwil", "8800", "ZH",
     "Director Operations", "MSc El.-Ing.", "info@u-blox.com",
     "+41 44 722 74 44", "https://www.u-blox.com",
     "GPS-Module + IoT", "USV Engineering; PQ", "USV",
     "Adr: Zürcherstrasse 68, 8800 Thalwil", "GPS-Module"),
    ("A", "Industrie/Maschinenbau", "Bobst Group SA", "Mex", "1031", "VD",
     "Director Operations", "MSc Maschinenbau", "info@bobst.com",
     "+41 21 621 21 11", "https://www.bobst.com",
     "Verpackungsmaschinen; Werk Mex", "Generator Stage V; PQ Kl.A", "Generator",
     "Adr: Route de Faraz 3, 1031 Mex", "Verpackung"),
    ("A", "Industrie/Maschinenbau", "Oerlikon Surface Solutions AG", "Pfäffikon SZ", "8808", "SZ",
     "Director Operations", "MSc Materialwiss.", "info@oerlikon.com",
     "+41 58 360 96 96", "https://www.oerlikon.com",
     "Beschichtungstechnologie; PVD/CVD", "USV Beschichtungsanlagen; PQ", "USV",
     "Adr: Churerstrasse 120, 8808 Pfäffikon SZ", "Beschichtung"),
    ("B", "Industrie/Maschinenbau", "Datwyler Group", "Altdorf", "6460", "UR",
     "Director Operations CH", "MSc Polym.", "info@datwyler.com",
     "+41 41 875 11 00", "https://www.datwyler.com",
     "Dichtungen für Pharma + Auto", "Generator Stage V; PQ", "Generator",
     "Adr: Gotthardstrasse 31, 6460 Altdorf", "Dichtungs-Spezialist"),
    ("B", "Industrie/Maschinenbau", "Reichle & De-Massari AG (R&M)", "Wetzikon", "8623", "ZH",
     "Director Operations", "Dipl. El.-Ing.", "info@rdm.com",
     "+41 44 933 81 11", "https://www.rdm.com",
     "Netzwerk-Verkabelung; RZ-Komponenten", "USV; PQ-Analyse", "PQ-Analyse",
     "Adr: Binzstrasse 32, 8623 Wetzikon", "Verkabelung"),
    ("A", "Industrie/Maschinenbau", "Tetra Pak Schweiz AG", "Romont", "1680", "FR",
     "Director Plant Operations", "MSc Chem.-Ing.", "info.ch@tetrapak.com",
     "+41 26 651 99 11", "https://www.tetrapak.com",
     "Verpackungssysteme Lebensmittel", "Generator + USV; ISO 50001", "Generator",
     "Adr: Route de Romont, 1680 Romont", "Verpackung Food"),

    # ============ Lebensmittel / Food (vergrössern) ============
    ("A", "Lebensmittel/Food", "Mibelle Group (Migros Industrie)", "Buchs AG", "5033", "AG",
     "Leiter Werksinstandhaltung", "Dipl. El.-Ing.", "info@mibellegroup.com",
     "+41 62 836 51 11", "https://www.mibellegroup.com",
     "Kosmetik + Reinigungsmittel Migros", "Generator; Kälte für Reinraum", "Generator",
     "Adr: Bolimattstrasse 1, 5033 Buchs AG", "Migros-Industrie"),
    ("A", "Lebensmittel/Food", "Bischofszell Nahrungsmittel AG", "Bischofszell", "9220", "TG",
     "Leiter Werksinstandhaltung", "Dipl. El.-Ing.", "info@bina.ch",
     "+41 71 424 91 11", "https://www.bina.ch",
     "Migros Industrie; Konserven + TK", "Kälte + Generator; PQ", "Kälte",
     "Adr: Industriestrasse, 9220 Bischofszell", "Migros-Industrie TG"),
    ("A", "Lebensmittel/Food", "Estavayer Lait SA (ELSA)", "Estavayer-le-Lac", "1470", "FR",
     "Director Operations", "MSc Lebensm.", "info@elsa.ch",
     "+41 26 663 91 11", "https://www.elsa.ch",
     "Migros Industrie Molkerei", "Kälte 24/7; Generator; PQ", "Kälte",
     "Adr: Route d'Yverdon 22, 1470 Estavayer-le-Lac", "Migros-Industrie FR"),
    ("A", "Lebensmittel/Food", "Emmi Schweiz AG (Luzern HQ)", "Luzern", "6005", "LU",
     "Director Real Estate", "Dipl. El.-Ing.", "info@emmi.com",
     "+41 58 227 27 27", "https://www.emmi.com",
     "Grösster Milchverarbeiter CH", "Kälte 24/7; Generator; PQ", "Kälte",
     "Adr: Landenbergstrasse 1, 6005 Luzern", "Milch-Konzern"),
    ("B", "Lebensmittel/Food", "Hilcona AG (Bendern, FL-Grenze)", "Bendern", "9487", "SG",
     "Director Operations", "MSc Lebensm.", "info@hilcona.com",
     "+41 81 750 02 22", "https://www.hilcona.com",
     "Convenience Food; Kälte intensive", "Kälte + Generator + PQ", "Kälte",
     "Adr: Bendererstrasse 21, 9487 Bendern", "Bell Food Group"),

    # ============ Spital / Klinik ============
    ("A", "Spital/Klinik", "Stadtspital Zürich (Triemli + Waid)", "Zürich", "8063", "ZH",
     "Leiter Facility Management", "MSc El.-Ing.", "info@stadtspital.ch",
     "+41 44 416 11 11", "https://www.stadtspital.ch",
     "2 Standorte Triemli/Waid; NIV Art.13", "NEA 5 MVA pro Standort; USV OP", "Notstrom/USV",
     "Adr: Birmensdorferstrasse 497, 8063 Zürich", "Zürcher Stadtspital"),
    ("A", "Spital/Klinik", "Hirslanden AG (Gruppen-HQ)", "Glattpark", "8152", "ZH",
     "Leiter Technik Group", "MSc El.-Ing.", "info@hirslanden.ch",
     "+41 44 388 85 85", "https://www.hirslanden.ch",
     "17 Privatkliniken CH; konzernweit", "USV + NEA pro Standort; Konzernvertrag", "Notstrom/USV",
     "Adr: Boulevard Lilienthal 2, 8152 Glattpark", "Privatklinik-Gruppe"),
    ("A", "Spital/Klinik", "Lindenhof AG (Lindenhof+Sonnenhof+Engeried)", "Bern", "3012", "BE",
     "Leiter Technik", "MSc El.-Ing.", "info@lindenhofgruppe.ch",
     "+41 31 300 88 11", "https://www.lindenhofgruppe.ch",
     "3 Standorte BE; NIV Art.13", "NEA 4 MVA Lindenhof; USV", "Notstrom/USV",
     "Adr: Bremgartenstrasse 117, 3012 Bern", "Privatklinik BE"),
    ("A", "Spital/Klinik", "Claraspital Basel", "Basel", "4002", "BS",
     "Leiter Technik", "MSc El.-Ing.", "info@claraspital.ch",
     "+41 61 685 85 85", "https://www.claraspital.ch",
     "NIV Art.13; Onkologie + Bauch", "NEA 2 MVA; USV OP", "Notstrom/USV",
     "Adr: Kleinriehenstrasse 30, 4002 Basel", "Privatklinik BS"),
    ("A", "Spital/Klinik", "Klinik Hirslanden Zürich (Witellikerstrasse)", "Zürich", "8032", "ZH",
     "Leiter Technik", "MSc El.-Ing.", "info.hzu@hirslanden.ch",
     "+41 44 387 21 11", "https://www.hirslanden.ch/zuerich",
     "Privatklinik #1 ZH; Herzzentrum", "NEA 3 MVA; USV Herz-OP", "Notstrom/USV",
     "Adr: Witellikerstrasse 40, 8032 Zürich", "Hirslanden Flagship"),
    ("A", "Spital/Klinik", "Klinik Im Park (Hirslanden)", "Zürich", "8027", "ZH",
     "Leiter Technik", "MSc El.-Ing.", "info.kip@hirslanden.ch",
     "+41 44 209 21 11", "https://www.hirslanden.ch/impark",
     "Privatklinik Zürich Seefeld", "USV OP-Säle; NEA 1.5 MVA", "Notstrom/USV",
     "Adr: Seestrasse 220, 8027 Zürich", "Hirslanden Seefeld"),
    ("B", "Spital/Klinik", "Spital Bülach AG", "Bülach", "8180", "ZH",
     "Leiter Technik", "Dipl. El.-Ing.", "info@spitalbuelach.ch",
     "+41 44 863 21 11", "https://www.spitalbuelach.ch",
     "Regionalspital Unterland ZH", "NEA 1.5 MVA; USV", "Notstrom/USV",
     "Adr: Spitalstrasse 24, 8180 Bülach", "Regionalspital ZH"),
    ("B", "Spital/Klinik", "Spitäler fmi AG", "Interlaken", "3800", "BE",
     "Leiter Technik", "Dipl. El.-Ing.", "info@spitalfmi.ch",
     "+41 33 826 26 26", "https://www.spitalfmi.ch",
     "Frutigen-Meiringen-Interlaken; 3 Standorte", "NEA pro Standort; Tourismus", "Notstrom/USV",
     "Adr: Weissenaustrasse 27, 3800 Unterseen", "Berner Oberland"),
    ("A", "Spital/Klinik", "Schulthess Klinik (Zürich)", "Zürich", "8008", "ZH",
     "Leiter Technik", "MSc El.-Ing.", "info@kws.ch",
     "+41 44 385 71 71", "https://www.schulthess-klinik.ch",
     "Orthopädie #1 CH", "USV OP; NEA 1.5 MVA", "Notstrom/USV",
     "Adr: Lengghalde 2, 8008 Zürich", "Orthopädie-Spezialist"),

    # ============ Bau / Infrastruktur ============
    ("A", "Bau/Infrastruktur", "Marti Holding AG", "Bern", "3001", "BE",
     "Leiter Maschinenpark", "Dipl. El.-Ing.", "info@martiag.ch",
     "+41 31 388 11 88", "https://www.martiag.ch",
     "Grossbau + Tunnel CH", "Baustromverteiler; Generator Stage V; IBC", "Generator",
     "Adr: Seedorfstrasse 40, 3001 Bern | Top-5 CH-Bauunternehmen", "Tunnelbau"),
    ("A", "Bau/Infrastruktur", "Frutiger AG", "Thun", "3603", "BE",
     "Leiter Maschinenpark", "Dipl. El.-Ing.", "info@frutiger.com",
     "+41 33 226 66 66", "https://www.frutiger.com",
     "Hoch- + Tiefbau BE/OW/NW", "Generator + Baustromverteiler", "Generator",
     "Adr: Frutigenstrasse 37, 3603 Thun", "Top-Bauunternehmen BE"),
    ("A", "Bau/Infrastruktur", "Walo Bertschinger AG", "Zürich", "8050", "ZH",
     "Leiter Maschinenpark", "Dipl. El.-Ing.", "info@walo.com",
     "+41 44 745 22 11", "https://www.walo.com",
     "Strassen + Hochbau", "Generator Stage V; Baustrom", "Generator",
     "Adr: Hagenholzstrasse 65, 8050 Zürich", "Strassenbau"),
    ("A", "Bau/Infrastruktur", "Eberhard Bau AG", "Kloten", "8302", "ZH",
     "Leiter Maschinenpark", "Dipl. El.-Ing.", "info@eberhard.ch",
     "+41 44 815 77 77", "https://www.eberhard.ch",
     "Rückbau + Recycling + Tiefbau", "Baustromverteiler; Generator", "Generator",
     "Adr: Steinackerstrasse 56, 8302 Kloten", "Rückbau-Spezialist"),
    ("A", "Bau/Infrastruktur", "HRS Real Estate AG", "Frauenfeld", "8500", "TG",
     "Leiter Realisierung", "MSc Bauing.", "info@hrs.ch",
     "+41 52 728 80 80", "https://www.hrs.ch",
     "Total-Unternehmer Schweiz", "Baustrom Grossprojekte; Generator", "Generator",
     "Adr: Walzmühlestrasse 48, 8500 Frauenfeld", "Total-Unternehmer"),
    ("B", "Bau/Infrastruktur", "Allreal Holding AG", "Zürich", "8048", "ZH",
     "Leiter Asset Management", "MBA", "info@allreal.ch",
     "+41 44 319 12 12", "https://www.allreal.ch",
     "Generalunternehmer + Immobilien", "Baustellengenerator + Notstrom", "Generator",
     "Adr: Grafenauweg 10, 8048 Zürich", "GU + REIT"),
    ("B", "Bau/Infrastruktur", "Implenia Tunnelbau AG", "Dietlikon", "8305", "ZH",
     "Leiter Tunnel", "MSc Bauing.", "info@implenia.com",
     "+41 58 474 74 74", "https://www.implenia.com",
     "Tunnel- + Spezialtiefbau", "Tunnel-Notstrom; BESS für Baustellen", "BESS + Generator",
     "Adr: Industriestrasse 24, 8305 Dietlikon", "Tunnelbauer"),

    # ============ Elektroplaner / Engineering ============
    ("B", "Elektroplaner/Engineering", "Amstein + Walthert AG", "Zürich", "8050", "ZH",
     "Partner Elektroplanung", "Dipl. El.-Ing.", "info@amstein-walthert.ch",
     "+41 44 305 91 11", "https://www.amstein-walthert.ch",
     "Top-Elektroplaner CH; RZ + Spital", "Planungspartner für BESS-Projekte", "PQ-Analyse",
     "Adr: Andreasstrasse 11, 8050 Zürich", "Top-Planer"),
    ("B", "Elektroplaner/Engineering", "Basler & Hofmann AG", "Zürich", "8032", "ZH",
     "Leiter Energietechnik", "Dipl. El.-Ing.", "info@baslerhofmann.ch",
     "+41 44 387 11 22", "https://www.baslerhofmann.ch",
     "Ingenieurbüro Energietechnik", "Beratung für PQ + BESS", "PQ-Analyse",
     "Adr: Forchstrasse 395, 8032 Zürich", "Top-Planer"),
    ("B", "Elektroplaner/Engineering", "Ernst Basler + Partner (EBP)", "Zollikon", "8702", "ZH",
     "Leiter Elektrotechnik", "Dipl. El.-Ing.", "info@ebp.ch",
     "+41 44 395 11 11", "https://www.ebp.ch",
     "Engineering CH/Int.", "Energie-Engineering, BESS-Planung", "PQ-Analyse",
     "Adr: Mühlebachstrasse 11, 8702 Zollikon", "Engineering"),
    ("B", "Elektroplaner/Engineering", "BG Ingénieurs Conseils SA", "Lausanne", "1003", "VD",
     "Director Energy", "MSc El.-Ing.", "info@bg-21.com",
     "+41 21 618 11 11", "https://www.bg-21.com",
     "Top-Planer Romandie", "BESS + Notstrom-Planung", "PQ-Analyse",
     "Adr: Avenue de Cour 61, 1003 Lausanne", "Top-Planer VD"),

    # ============ Forschung / Bildung ============
    ("A", "Forschung/Bildung", "Empa (Eidg. Materialprüfungsanstalt)", "Dübendorf", "8600", "ZH",
     "Leiter Facility Management", "Dr. El.-Ing.", "info@empa.ch",
     "+41 58 765 11 11", "https://www.empa.ch",
     "Forschungslabore; NEA Reinraum", "USV + NEA 2 MVA; PQ", "USV",
     "Adr: Überlandstrasse 129, 8600 Dübendorf", "Materialforschung"),
    ("A", "Forschung/Bildung", "WSL (Eidg. Forschungsanstalt Wald)", "Birmensdorf", "8903", "ZH",
     "Leiter FM", "Dipl. El.-Ing.", "info@wsl.ch",
     "+41 44 739 21 11", "https://www.wsl.ch",
     "Forschung Wald/Klima", "Notstrom IT + Labor", "USV",
     "Adr: Zürcherstrasse 111, 8903 Birmensdorf", "ETH-Domain"),
    ("A", "Forschung/Bildung", "Universität Basel (Campus)", "Basel", "4001", "BS",
     "Leiter Bauten + Anlagen", "Dipl. El.-Ing.", "info@unibas.ch",
     "+41 61 207 11 11", "https://www.unibas.ch",
     "Campus + Biozentrum", "USV Forschung; NEA", "USV",
     "Adr: Petersplatz 1, 4001 Basel", "Universität"),
    ("A", "Forschung/Bildung", "Universität Zürich (UZH)", "Zürich", "8006", "ZH",
     "Leiter Immobilien", "Dipl. El.-Ing.", "info@uzh.ch",
     "+41 44 634 11 11", "https://www.uzh.ch",
     "Größte Uni CH; Spitalverbund USZ", "NEA 4 MVA Campus; USV", "Generator",
     "Adr: Rämistrasse 71, 8006 Zürich", "Universität"),
    ("A", "Forschung/Bildung", "Universität Bern", "Bern", "3012", "BE",
     "Leiter Bauten + Anlagen", "Dipl. El.-Ing.", "info@unibe.ch",
     "+41 31 684 11 11", "https://www.unibe.ch",
     "Campus + Inselspital-Verbund", "NEA + USV; ETH-nah", "Generator",
     "Adr: Hochschulstrasse 6, 3012 Bern", "Universität"),
    ("A", "Forschung/Bildung", "Universität St. Gallen (HSG)", "St. Gallen", "9000", "SG",
     "Leiter Infrastruktur", "Dipl. El.-Ing.", "info@unisg.ch",
     "+41 71 224 21 11", "https://www.unisg.ch",
     "WiWi-Uni HSG", "NEA Campus; USV", "Generator",
     "Adr: Dufourstrasse 50, 9000 St. Gallen", "Universität"),
    ("A", "Forschung/Bildung", "ETH Lausanne (EPFL Innovation Park)", "Lausanne", "1015", "VD",
     "Leiter Infrastruktur", "Dipl. El.-Ing.", "info.ip@epfl.ch",
     "+41 21 693 11 11", "https://www.epfl.ch",
     "Forschung + Spin-offs", "BESS + NEA; PQ Kl.A", "BESS",
     "Adr: Innovation Park, EPFL, 1015 Lausanne", "ETH-Domain"),

    # ============ Gemeinde / Öffentlich ============
    ("B", "Gemeinde/Öffentlich", "Die Schweizerische Post AG (Logistikzentrum)", "Härkingen", "4624", "SO",
     "Leiter Logistik-Engineering", "Dipl. El.-Ing.", "info@post.ch",
     "+41 58 386 49 06", "https://www.post.ch",
     "Briefzentrum CH-Mitte", "Notstrom Sortierungsanlage; PQ", "Generator",
     "Adr: Bösfeld 11, 4624 Härkingen", "Logistik-Zentrum"),
    ("B", "Gemeinde/Öffentlich", "DHL Express Schweiz AG", "Glattbrugg", "8152", "ZH",
     "Country Manager Operations", "MBA Logistik", "info.ch@dhl.com",
     "+41 800 800 145", "https://www.dhl.ch",
     "Express-Hub Zürich", "USV + NEA Hub", "Generator",
     "Adr: Hofwiesenstrasse 350, 8152 Glattbrugg", "Express-Logistik"),
    ("B", "Gemeinde/Öffentlich", "Planzer Holding AG", "Dietikon", "8953", "ZH",
     "Leiter Maschinenpark", "Dipl. El.-Ing.", "info@planzer.ch",
     "+41 44 745 35 35", "https://www.planzer.ch",
     "Top-3 Spediteur CH", "Notstrom Verteilzentren; Kälte für Tiefkühl", "Kälte",
     "Adr: Lerzenstrasse 16, 8953 Dietikon", "Spedition"),
    ("B", "Gemeinde/Öffentlich", "BLS AG (Bahninfrastruktur)", "Bern", "3000", "BE",
     "Leiter Bahnstromversorgung", "Dipl. El.-Ing.", "info@bls.ch",
     "+41 58 327 31 11", "https://www.bls.ch",
     "Bahnnetz BE/VS/JU; Lötschberg", "Tunnel-Notstrom; PQ; mobile MS", "Mobile MS-Verteilung",
     "Adr: Genfergasse 11, 3000 Bern", "Bahn-EVU"),
    ("B", "Gemeinde/Öffentlich", "Skyguide", "Wangen bei Dübendorf", "8602", "ZH",
     "Leiter Critical Infrastructure", "MSc El.-Ing.", "info@skyguide.ch",
     "+41 43 931 61 11", "https://www.skyguide.ch",
     "Flugsicherung CH; Tower + Center", "USV Klasse A; NEA 2 MVA", "USV",
     "Adr: Ifangstrasse 30, 8602 Wangen-Dübendorf", "Critical Infra"),
    ("A", "Gemeinde/Öffentlich", "Genève Aéroport (GVA)", "Cointrin", "1215", "GE",
     "Director Engineering", "MSc El.-Ing.", "info@gva.ch",
     "+41 22 717 71 11", "https://www.gva.ch",
     "Flughafen Genf; Rollfeld + Terminal", "Notstrom Rollfeld; BESS; USV", "BESS + Generator",
     "Adr: Route de l'Aéroport 21, 1215 Cointrin", "Flughafen GE"),
    ("B", "Gemeinde/Öffentlich", "EuroAirport Basel-Mulhouse", "Basel", "4030", "BS",
     "Director Engineering", "MSc El.-Ing.", "info@euroairport.com",
     "+33 3 89 90 31 11", "https://www.euroairport.com",
     "Binational Airport BS/F", "Tower-USV; Rollfeld-Notstrom", "USV",
     "Adr: Postfach, 4030 Basel-Flughafen", "Trinationaler Airport"),
    ("B", "Gemeinde/Öffentlich", "Stadtpolizei + Schutz & Rettung Zürich", "Zürich", "8004", "ZH",
     "Leiter Technik", "Dipl. El.-Ing.", "info@stadt-zuerich.ch",
     "+41 44 411 21 21", "https://www.stadt-zuerich.ch/sru",
     "Blaulicht-Organisation; Krisenstab", "NEA Leitstelle; USV Funk", "Notstrom/USV",
     "Adr: Neumühlequai 4, 8004 Zürich", "Blaulicht"),

    # ============ Bergbahn / Tourismus ============
    ("B", "Bergbahn/Tourismus", "Jungfraubahnen Holding AG", "Interlaken", "3800", "BE",
     "Leiter Technik", "Dipl. El.-Ing.", "info@jungfrau.ch",
     "+41 33 828 72 33", "https://www.jungfrau.ch",
     "Top of Europe; höchstgelegene Bahn", "Notstrom Hochgebirge; BESS", "BESS + Generator",
     "Adr: Höheweg 35, 3800 Interlaken", "Top-Tourismus"),
    ("B", "Bergbahn/Tourismus", "Zermatt Bergbahnen AG", "Zermatt", "3920", "VS",
     "Leiter Technik", "Dipl. El.-Ing.", "info@matterhornparadise.ch",
     "+41 27 966 01 01", "https://www.matterhornparadise.ch",
     "Matterhorn Glacier Paradise", "Notstrom Bergstation; Wärme", "Generator",
     "Adr: Bahnhofplatz 7, 3920 Zermatt", "Top-Tourismus VS"),
    ("B", "Bergbahn/Tourismus", "Weisse Arena Gruppe (Laax)", "Laax", "7032", "GR",
     "Leiter Technik", "Dipl. El.-Ing.", "info@laax.com",
     "+41 81 927 70 70", "https://www.laax.com",
     "Skigebiet + Hotels Flims/Laax", "Beschneiungsanlage; Notstrom", "Generator",
     "Adr: Via Murschetg 17, 7032 Laax", "Top-Skigebiet"),
    ("B", "Bergbahn/Tourismus", "Bürgenstock Hotels & Resort", "Obbürgen", "6363", "NW",
     "Director Engineering", "Dipl. El.-Ing.", "info@buergenstock.ch",
     "+41 41 612 60 00", "https://www.buergenstock.ch",
     "Luxus-Resort NW; Bühne G7-Treffen", "USV + NEA 1.5 MVA", "Notstrom/USV",
     "Adr: Bürgenstock 22, 6363 Obbürgen", "Top-Resort"),

    # ============ Events / Messen ============
    ("B", "Events/Messen", "MCH Group AG (Messe Schweiz)", "Basel", "4005", "BS",
     "Director Event Operations", "MSc El.-Ing.", "info@mch-group.com",
     "+41 58 200 20 20", "https://www.mch-group.com",
     "Messe Basel + Zürich; Art Basel", "Mobile Generator + Verteilung", "Generator",
     "Adr: Messeplatz 10, 4005 Basel", "Messe-Veranstalter"),
    ("B", "Events/Messen", "Bernexpo AG", "Bern", "3000", "BE",
     "Director Operations", "Dipl. El.-Ing.", "info@bernexpo.ch",
     "+41 31 340 11 11", "https://www.bernexpo.ch",
     "BEA + OLMA-Schwester BE", "Mobile Stromverteilung", "Mobile MS-Verteilung",
     "Adr: Mingerstrasse 6, 3000 Bern", "Messe BE"),
    ("B", "Events/Messen", "Palexpo SA", "Le Grand-Saconnex", "1218", "GE",
     "Director Engineering", "Dipl. El.-Ing.", "info@palexpo.ch",
     "+41 22 761 11 11", "https://www.palexpo.ch",
     "Messe Genf; Auto-Salon", "NEA + Mobile MS", "Generator",
     "Adr: Route François-Peyrot 30, 1218 Le Grand-Saconnex", "Messe GE"),
]
