ROWS = [
    [1, 'Beine vorne', 'Adduktion', 'W', 77.5, 17, None, None],
    [1, 'Beine vorne', 'Adduktion', 'A', 152.5, 17, None, None],
    [1, 'Beine vorne', 'Adduktion', 'A', 152.5, 10, None, None],
    [1, 'Beine vorne', 'Adduktion', 'R', 110, 10, '110 / 72.5', None],
    [2, 'Beine vorne', 'Adduktion', 'W', 85, 10, None, None],
    [2, 'Beine vorne', 'Adduktion', 'A', 152.5, 20, None, None],
    [2, 'Beine vorne', 'Adduktion', 'A', 152.5, 16, None, None],
    [2, 'Beine vorne', 'Adduktion', 'R', 110, 10, '110 / 72.5 / 35', None],
    [3, 'Beine vorne', 'Adduktion', 'W', 65, 10, None, None],
    [3, 'Beine vorne', 'Adduktion', 'W', 80, 6, None, None],
    [3, 'Beine vorne', 'Adduktion', 'A', 152.5, 22, None, None],
    [3, 'Beine vorne', 'Adduktion', 'A', 152.5, 13, None, None],
    [3, 'Beine vorne', 'Adduktion', 'R', 110, 10, '110 / 72.5 / 35 / 20', None],
    [4, 'Beine vorne', 'Adduktion', 'W', 50, 10, None, None],
    [4, 'Beine vorne', 'Adduktion', 'W', 70, 10, None, None],
    [4, 'Beine vorne', 'Adduktion', 'A', 152.5, 25, None, 'Original 152.2, als Tippfehler gewertet'],
    [4, 'Beine vorne', 'Adduktion', 'A', 152.5, 20, None, 'Original 152.2, als Tippfehler gewertet'],
    [4, 'Beine vorne', 'Adduktion', 'R', 125, 6, '125 / 110 / 95 / 80', None],
    [1, 'Beine vorne', 'Beinstrecker', 'W', 15, 10, None, None],
    [1, 'Beine vorne', 'Beinstrecker', 'W', 30, 4, None, None],
    [1, 'Beine vorne', 'Beinstrecker', 'A', 65, 7, None, None],
    [1, 'Beine vorne', 'Beinstrecker', 'A', 75, 10, None, None],
    [1, 'Beine vorne', 'Beinstrecker', 'R', 55, None, '55 / 45 / 30 / 15', 'Original 10-5 Wdh, Zuordnung unklar'],
    [2, 'Beine vorne', 'Beinstrecker', 'W', 10, None, None, 'Original: W 10kg 20kg 5-6wdh, Zuordnung unklar'],
    [2, 'Beine vorne', 'Beinstrecker', 'W', 20, None, None, 'Original: W 10kg 20kg 5-6wdh, Zuordnung unklar'],
    [2, 'Beine vorne', 'Beinstrecker', 'A', 70, 13, None, None],
    [2, 'Beine vorne', 'Beinstrecker', 'A', 80, 9, None, None],
    [2, 'Beine vorne', 'Beinstrecker', 'R', 60, 10, '60 / 45 / 30 / 15 / 15', None],
    [3, 'Beine vorne', 'Beinstrecker', 'W', 15, 6, None, None],
    [3, 'Beine vorne', 'Beinstrecker', 'W', 25, 5, None, None],
    [3, 'Beine vorne', 'Beinstrecker', 'A', 85, 8, None, None],
    [3, 'Beine vorne', 'Beinstrecker', 'A', 75, 10, None, None],
    [3, 'Beine vorne', 'Beinstrecker', 'R', 65, 10, '65 / 55 / 45 / 35 / 25 / 15', None],
    [4, 'Beine vorne', 'Beinstrecker', 'W', 15, 10, None, None],
    [4, 'Beine vorne', 'Beinstrecker', 'W', 30, 5, None, None],
    [4, 'Beine vorne', 'Beinstrecker', 'A', 80, 12, None, None],
    [4, 'Beine vorne', 'Beinstrecker', 'A', 80, 8, None, None],
    [4, 'Beine vorne', 'Beinstrecker', 'R', 70, 6, '70 / 60 / 45 / 30 / 15', None],
    [1, 'Beine vorne', 'Split Squat', 'W', 20, 5, None, None],
    [1, 'Beine vorne', 'Split Squat', 'W', 40, 5, None, None],
    [1, 'Beine vorne', 'Split Squat', 'A', 80, 6, None, None],
    [1, 'Beine vorne', 'Split Squat', 'A', 90, 7, None, None],
    [1, 'Beine vorne', 'Split Squat', 'A', 100, 5, None, None],
    [2, 'Beine vorne', 'Split Squat', 'W', 30, 5, None, None],
    [2, 'Beine vorne', 'Split Squat', 'W', 50, 3, None, None],
    [2, 'Beine vorne', 'Split Squat', 'A', 85, 8, None, None],
    [2, 'Beine vorne', 'Split Squat', 'A', 95, 5, None, None],
    [2, 'Beine vorne', 'Split Squat', 'A', 105, 4, None, None],
    [3, 'Beine vorne', 'Split Squat', 'W', 40, 5, None, None],
    [3, 'Beine vorne', 'Split Squat', 'W', 60, 3, None, None],
    [3, 'Beine vorne', 'Split Squat', 'A', 100, 7, None, None],
    [3, 'Beine vorne', 'Split Squat', 'A', 95, 9, None, None],
    [3, 'Beine vorne', 'Split Squat', 'A', 90, 8, None, None],
    [4, 'Beine vorne', 'Split Squat', 'W', 40, 6, None, None],
    [4, 'Beine vorne', 'Split Squat', 'W', 70, 3, None, None],
    [4, 'Beine vorne', 'Split Squat', 'A', 80, 8, None, None],
    [4, 'Beine vorne', 'Split Squat', 'A', 60, 10, None, None],
    [4, 'Beine vorne', 'Split Squat', 'A', 50, 8, None, None],
    [1, 'Beine vorne', 'Lunges', 'A', 10, None, None, 'Wdh fehlt im Original'],
    [2, 'Beine vorne', 'Lunges', 'A', 16, None, None, 'Wdh fehlt im Original'],
    [3, 'Beine vorne', 'Lunges', 'A', 18, None, None, 'Wdh fehlt im Original'],
    [1, 'Beine hinten', 'Kickback', 'W', 35, None, None, 'Wdh fehlt im Original'],
    [1, 'Beine hinten', 'Kickback', 'W', 49, None, None, 'Wdh fehlt im Original'],
    [1, 'Beine hinten', 'Kickback', 'A', 70, 15, None, None],
    [1, 'Beine hinten', 'Kickback', 'A', 77, 12, None, None],
    [2, 'Beine hinten', 'Kickback', 'W', 30, None, None, 'Wdh fehlt im Original'],
    [2, 'Beine hinten', 'Kickback', 'W', 42, None, None, 'Wdh fehlt im Original'],
    [2, 'Beine hinten', 'Kickback', 'A', 77, 10, None, None],
    [2, 'Beine hinten', 'Kickback', 'A', 84, 6, None, None],
    [3, 'Beine hinten', 'Kickback', 'W', 20, None, None, 'Wdh fehlt im Original'],
    [3, 'Beine hinten', 'Kickback', 'W', 30, None, None, 'Wdh fehlt im Original'],
    [3, 'Beine hinten', 'Kickback', 'A', 77, 14, None, None],
    [3, 'Beine hinten', 'Kickback', 'A', 84, 12, None, None],
    [4, 'Beine hinten', 'Kickback', 'W', 25, None, None, 'Wdh fehlt im Original'],
    [4, 'Beine hinten', 'Kickback', 'W', 35, None, None, 'Wdh fehlt im Original'],
    [4, 'Beine hinten', 'Kickback', 'A', 63, 15, None, None],
    [4, 'Beine hinten', 'Kickback', 'A', 56, 15, None, None],
    [1, 'Beine hinten', 'Seitliche Kickbacks', 'W', 15, 8, None, None],
    [1, 'Beine hinten', 'Seitliche Kickbacks', 'A', 49, 12, None, None],
    [1, 'Beine hinten', 'Seitliche Kickbacks', 'A', 35, 14, None, None],
    [2, 'Beine hinten', 'Seitliche Kickbacks', 'W', 25, 5, None, None],
    [2, 'Beine hinten', 'Seitliche Kickbacks', 'A', 35, 15, None, None],
    [2, 'Beine hinten', 'Seitliche Kickbacks', 'A', 30, 15, None, None],
    [1, 'Beine hinten', 'Beinbeuger', 'W', 25, 10, None, None],
    [1, 'Beine hinten', 'Beinbeuger', 'A', 45, 14, None, None],
    [1, 'Beine hinten', 'Beinbeuger', 'A', 50, 10, None, None],
    [1, 'Beine hinten', 'Beinbeuger', 'R', 30, 10, '30 / 20 / 10', None],
    [2, 'Beine hinten', 'Beinbeuger', 'W', 30, 10, None, None],
    [2, 'Beine hinten', 'Beinbeuger', 'A', 50, 12, None, None],
    [2, 'Beine hinten', 'Beinbeuger', 'A', 55, 10, None, None],
    [2, 'Beine hinten', 'Beinbeuger', 'R', 40, 8, '40 / 35 / 30', None],
    [3, 'Beine hinten', 'Beinbeuger', 'W', 35, 6, None, None],
    [3, 'Beine hinten', 'Beinbeuger', 'A', 45, 15, None, None],
    [3, 'Beine hinten', 'Beinbeuger', 'A', 40, 15, None, None],
    [3, 'Beine hinten', 'Beinbeuger', 'R', 30, 6, '30 / 25 / 20', None],
    [1, 'Beine hinten', 'Hip Thrust', 'W', 170, 10, None, 'Gesamtgewicht inkl. Stange'],
    [1, 'Beine hinten', 'Hip Thrust', 'A', 220, 12, None, None],
    [1, 'Beine hinten', 'Hip Thrust', 'A', 240, 8, None, None],
    [1, 'Beine hinten', 'Hip Thrust', 'R', None, 6, '-25 kg je Seite', 'Absolutgewicht im Original nicht notiert'],
    [2, 'Beine hinten', 'Hip Thrust', 'W', 180, 10, None, None],
    [2, 'Beine hinten', 'Hip Thrust', 'A', 240, 10, None, None],
    [2, 'Beine hinten', 'Hip Thrust', 'A', 280, 6, None, None],
    [2, 'Beine hinten', 'Hip Thrust', 'R', None, 6, '-25 kg je Seite', 'Absolutgewicht im Original nicht notiert'],
    [3, 'Beine hinten', 'Hip Thrust', 'W', 120, 5, None, None],
    [3, 'Beine hinten', 'Hip Thrust', 'W', 170, 4, None, None],
    [3, 'Beine hinten', 'Hip Thrust', 'A', 280, 8, None, None],
    [3, 'Beine hinten', 'Hip Thrust', 'A', 270, 10, None, None],
    [3, 'Beine hinten', 'Hip Thrust', 'R', None, 6, '-25 kg je Seite', 'Absolutgewicht im Original nicht notiert'],
    [4, 'Beine hinten', 'Hip Thrust', 'W', 120, 5, None, None],
    [4, 'Beine hinten', 'Hip Thrust', 'W', 170, 3, None, None],
    [4, 'Beine hinten', 'Hip Thrust', 'A', 270, 8, None, None],
    [4, 'Beine hinten', 'Hip Thrust', 'A', 270, 8, None, None],
    [4, 'Beine hinten', 'Hip Thrust', 'A', 270, 8, None, None],
    [1, 'Beine hinten', 'Waden', 'W', 65, 8, None, None],
    [1, 'Beine hinten', 'Waden', 'A', 145, 12, None, None],
    [1, 'Beine hinten', 'Waden', 'A', 115, 15, None, None],
    [2, 'Beine hinten', 'Waden', 'W', 67.5, 8, None, None],
    [2, 'Beine hinten', 'Waden', 'A', 150, 12, None, None],
    [2, 'Beine hinten', 'Waden', 'A', 140, 12, None, None],
    # --- Einheit 5 -------------------------------------------------
    [5, 'Beine hinten', 'Rumänisches Kreuzheben', 'W', 40, 10, None, None],
    [5, 'Beine hinten', 'Rumänisches Kreuzheben', 'W', 80, 4, None, None],
    [5, 'Beine hinten', 'Rumänisches Kreuzheben', 'A', 110, 12, None, None],
    [5, 'Beine hinten', 'Rumänisches Kreuzheben', 'A', 110, 12, None, None],
    [5, 'Beine hinten', 'Rumänisches Kreuzheben', 'A', 110, 10, None, None],
    [5, 'Beine hinten', 'Hip Thrust', 'W', 125, 8, None, 'Langhantel'],
    [5, 'Beine hinten', 'Hip Thrust', 'A', 150, 12, None, None],
    [5, 'Beine hinten', 'Hip Thrust', 'A', 170, 10, None, None],
    [5, 'Beine hinten', 'Hip Thrust', 'A', 190, 8, None, None],
    [5, 'Beine hinten', 'Beinbeuger', 'W', 20.5, 10, None, None],
    [5, 'Beine hinten', 'Beinbeuger', 'W', 32, 4, None, None],
    [5, 'Beine hinten', 'Beinbeuger', 'A', 45, 12, None, None],
    [5, 'Beine hinten', 'Beinbeuger', 'A', 45, 12, None, None],
    [5, 'Beine hinten', 'Beinbeuger', 'R', 30, 6, '30 / 25 / 20', None],
    [5, 'Beine hinten', 'Seitliche Kickbacks', 'W', 16, 5, None, None],
    [5, 'Beine hinten', 'Seitliche Kickbacks', 'A', 36, 10, None, None],
    [5, 'Beine hinten', 'Seitliche Kickbacks', 'A', 36, 10, None, None],
    [5, 'Beine hinten', 'Waden', 'W', 70, 5, None, None],
    [5, 'Beine hinten', 'Waden', 'W', 108, 3, None, None],
    [5, 'Beine hinten', 'Waden', 'A', 135, 11, None, None],
    [5, 'Beine hinten', 'Waden', 'A', 135, 12, None, None],
    [5, 'Beine vorne', 'Split Squat', 'W', 40, 4, None, None],
    [5, 'Beine vorne', 'Split Squat', 'W', 60, 3, None, None],
    [5, 'Beine vorne', 'Split Squat', 'A', 100, 8, None, None],
    [5, 'Beine vorne', 'Split Squat', 'A', 80, 12, None, 'absteigend'],
    [5, 'Beine vorne', 'Beinpresse', 'W', 103, 6, None, None],
    [5, 'Beine vorne', 'Beinpresse', 'W', 153, 5, None, None],
    [5, 'Beine vorne', 'Beinpresse', 'A', 253, 12, None, None],
    [5, 'Beine vorne', 'Beinpresse', 'A', 273, 10, None, None],
    [5, 'Beine vorne', 'Beinstrecker', 'W', 35, 5, None, None],
    [5, 'Beine vorne', 'Beinstrecker', 'W', 55, 3, None, None],
    [5, 'Beine vorne', 'Beinstrecker', 'A', 80, 10, None, None],
    [5, 'Beine vorne', 'Beinstrecker', 'A', 70, 11, None, 'absteigend'],
    [5, 'Beine vorne', 'Beinstrecker', 'R', 50, None, '50 / 25', 'Wdh nicht notiert'],
    [5, 'Beine vorne', 'Adduktion', 'W', 70, 5, None, None],
    [5, 'Beine vorne', 'Adduktion', 'A', 162.5, 16, None, None],
    [5, 'Beine vorne', 'Adduktion', 'A', 162.5, None, None, 'Wdh nicht notiert'],
]
