# Datenbasis Zielkundenliste Schweiz (Recherche Stand 27.09.2026)
# Felder: kat, firma, mutter, ort, kt, reg, sprache, web, groesse, anlass, produkte, warum,
#         fit, vol, timing, zugang, kern, gl, quelle, validierung

R = {"W": "West (Romandie)", "M": "Mittelland/Bern", "N": "Nordwestschweiz", "Z": "Zürich",
     "O": "Ostschweiz", "C": "Zentralschweiz", "T": "Tessin"}

INST = "Installateur"
FM, EVU, PLAN = "Facility Manager", "Stadtwerk/EVU", "Elektroplaner"
GU, RZ, IND, SPI, INF, EVT = "GU/TU", "Rechenzentrum", "Industrie", "Spital", "Infrastruktur", "Event"

D = [
# ---------------- INSTALLATEURE ----------------
(INST, "Burkhalter Gruppe (Holding)", "börsenkotiert", "Zürich", "ZH", "Z", "DE", "burkhalter.ch",
 "5'356 FTE, 83 Gesellschaften, 169 Standorte (31.12.2025)", "",
 "Baustrom, Generator, USV, NEA-Test", "Grösster Elektroinstallateur CH. Ein Rahmenvertrag öffnet Dutzende Töchter (u.a. Sedelec, Mérinat, EAGB, Hufschmid, Celio, Grichting & Valterio).",
 5, 5, 4, 3, "Ja", "CEO Zeno Böhm (Moneycab)", "https://ch.marketscreener.com/boerse-nachrichten/burkhalter-kurzversion-nichtfinanzielle-berichterstattung-2025-ce7e50ded98bf423", ""),
(INST, "Equans Switzerland AG", "Bouygues (ex Bouygues E&S InTec / Alpiq InTec)", "Zürich", "ZH", "Z", "DE", "equans.ch",
 ">1'600 MA, >20 Standorte (Broschüre 2025, Zahl prüfen)", "",
 "Generator, Trafo, NEA-Test, USV, Baustrom", "Energie, Verkehr, Industrie und FM unter einem Dach: NEA-Tests, Service-Unterbrüche, temporäre Einspeisung.",
 5, 5, 4, 3, "Ja", "", "https://www.phase5.ch/nun-heisst-es-offiziell-equans-switzerland", "Seit 07/2024 unter diesem Namen. MA-Zahl wirkt tief, prüfen."),
(INST, "Kummler+Matter EVT AG", "Equans Switzerland (inkl. Mauerhofer & Zuber)", "Zürich", "ZH", "Z", "DE/FR", "kuma-evt.ch",
 "k.A.", "",
 "Generator, BESS, Trafo", "Netz- und Freileitungsbau, Bahnstrom. Hat eigene mobile Trafostationen: Partner bei Spitzen, zugleich Wettbewerber.",
 4, 4, 3, 3, "Ja", "", "https://kuma-evt.ch/de/ueber-uns", "Partner- oder Wettbewerberrolle intern klären."),
(INST, "ETAVIS AG", "VINCI Energies", "Zürich", "ZH", "Z", "DE", "etavis.ch",
 ">2'400 MA", "",
 "Baustrom, Generator, USV, NEA-Test", "Landesweit in Infrastruktur (Flughafen, Tunnel, Bahn) und Rechenzentren. Zugang zu VINCI-Schwestern (Actemium, Gfeller).",
 5, 5, 4, 3, "Ja", "", "https://www.vinci-energies.ch/unsere-bereiche/etavis/", ""),
(INST, "ETAVIS Kriegel+Schaffner AG", "VINCI Energies / ETAVIS", "Basel", "BS", "N", "DE", "etavis.ch",
 "ca. 700 MA Region NWCH (prüfen)", "Pharma-Grossprojekte Basel (Roche Bau 12, Bachem)",
 "USV, Generator, NEA-Test, Trafo", "Pharma und Chemie Basel: Shutdowns, Umbauten unter GMP, hohe Ausfallkosten beim Endkunden.",
 5, 4, 4, 3, "Ja", "", "https://www.moneyhouse.ch/en/company/etavis-kriegel-schaffner-ag-2862953081", ""),
(INST, "ETAVIS Grossenbacher AG", "VINCI Energies / ETAVIS", "St. Gallen", "SG", "O", "DE", "etavis.ch",
 "k.A.", "",
 "Baustrom, Generator", "Ostschweizer Grossbaustellen und Industrie, Einstieg über ETAVIS-Rahmen.",
 4, 4, 3, 3, "Ja", "", "https://www.ostjob.ch/firma/etavis-grossenbacher-ag/37152", ""),
(INST, "ETAVIS Elettro-Impianti SA", "VINCI Energies / ETAVIS", "Pregassona-Lugano", "TI", "T", "IT", "etavis.ch/it",
 "k.A.", "2. Gotthardröhre Süd (Airolo) im Umfeld",
 "Baustrom, Generator, Trafo", "Tessiner Grossprojekte und Tunnel. Einer der wenigen grösseren Installateure im Tessin.",
 4, 3, 4, 3, "Ja", "", "https://www.moneyhouse.ch/en/company/etavis-elettro-impianti-sa-3148976161", "Tunnelbezug unbestätigt."),
(INST, "Gfeller Elektro AG", "VINCI Energies / ETAVIS (seit 2022)", "Bern", "BE", "M", "DE", "",
 "ca. 90-100 MA", "",
 "Baustrom, Generator", "Gewerbe- und Verwaltungsbauten Bern. Kleinere Volumen, guter Zugang.",
 3, 2, 3, 4, "Ja", "", "https://www.vinci-energies.ch/pressemitteilung/gfeller-elektro-uebernahme/", ""),
(INST, "Actemium Schweiz AG", "VINCI Energies (ex Cegelec)", "Ittigen", "BE", "M", "DE/FR", "actemium.ch",
 "ca. 930 MA (prüfen)", "",
 "Generator, Lastbank/NEA-Test, Trafo, USV", "Industrieautomation und Prozessanlagen: Shutdowns, Inbetriebnahmen, Lastbanktests.",
 5, 4, 4, 3, "Ja", "", "https://www.moneyhouse.ch/en/company/actemium-schweiz-ag-20686058021", ""),
(INST, "BKW Building Solutions AG", "BKW", "Ostermundigen", "BE", "M", "DE/FR", "bkw.ch",
 "ca. 4'000 MA in ca. 50 Firmen", "",
 "Baustrom, BESS, Generator", "Dach von AEK, ISP, swisspro, Arnold, inelectro. Zentraler Einkaufsrahmen für Baustrom und BESS.",
 5, 5, 3, 3, "Ja", "", "https://www.bkw.com/en/about-us/building-solutions", "BKW ist Lauberhorn-Sponsor: Nähe zu Energiethemen, evtl. Eigenlösungen."),
(INST, "Arnold AG", "BKW (Infra Services)", "Wangen an der Aare", "BE", "M", "DE", "arnold.ch",
 "ca. 1'000 MA Infra-Services-Gruppe", "",
 "Trafo, Generator, Netzersatz", "Hochspannungs- und Kabelnetzbau: Ersatzversorgung bei Netzumbauten, Trafo-Miete.",
 5, 4, 4, 3, "Ja", "", "https://www.arnold.ch/unternehmen/", ""),
(INST, "BKW ISP AG", "BKW", "Oberhofen am Thunersee (prüfen)", "BE", "M", "DE", "bkw.ch",
 "200-499 MA (uneinheitlich)", "",
 "Baustrom, Generator", "Elektroinstallation und PV im Raum Bern.",
 3, 3, 3, 3, "Ja", "", "https://www.bkw.ch/de/ueber-uns/aktuell/medien/medienmitteilungen/bkw-isp-gruppe-weitet-elektroinstallationsgeschaeft-aus", "Sitz prüfen."),
(INST, "swisspro AG", "BKW (seit 2019)", "Urdorf", "ZH", "Z", "DE", "swisspro.ch",
 "ca. 430 MA (prüfen)", "",
 "USV, BESS", "ICT und Gebäudeautomation: USV bei Rechenzentrums- und Netzumbauten.",
 4, 3, 3, 3, "Ja", "", "https://www.bkw.ch/de/swisspro-ag", ""),
(INST, "AEK AG", "BKW (seit 2022)", "Solothurn", "SO", "M", "DE", "aek.ch",
 "ca. 250 MA", "",
 "NEA-Test, Baustrom, Generator", "Industrie Solothurn (z.B. Grossauftrag Bell).",
 4, 3, 3, 3, "Ja", "", "https://www.aek.ch/de", ""),
(INST, "inelectro sa", "BKW", "Porrentruy", "JU", "W", "FR", "inelectro.ch",
 "55 MA", "",
 "USV, Generator", "Jura-Industrie (Uhren, Präzision): USV bei geplanten Stromunterbrüchen.",
 3, 2, 3, 3, "Ja", "", "https://www.bkw.ch/fr/inelectro-sa", ""),
(INST, "cablex AG", "Swisscom", "Gümligen", "BE", "M", "DE/FR/IT", "cablex.ch",
 "ca. 2'300 MA", "",
 "BESS, Generator, USV", "Netzinfrastruktur und Mobilfunk landesweit: Notstrom für Antennen und Knoten, BESS für Umbauten.",
 5, 4, 3, 3, "Ja", "CEO Roger Keller (seit 01.01.2025, cablex.ch)", "https://www.cablex.ch/en/news/change-in-the-management-of-cablex", ""),
(INST, "Scherler AG, Elektro und Telematik", "unabhängig (Familie)", "Bern", "BE", "M", "DE", "scherler-ag.ch",
 "k.A.", "",
 "Baustrom, Generator", "Schaltanlagenbau und Installation Bern.",
 3, 2, 3, 4, "Ja", "", "https://www.scherler-ag.ch/", "Nicht verwechseln mit SCHERLER AG Luzern (Planer)."),
(INST, "CKW Gebäudetechnik AG", "CKW / Axpo", "Luzern", "LU", "C", "DE", "ckw.ch",
 "ca. 1'400 MA, 60 Standorte", "",
 "Baustrom, Generator, BESS", "Grösster Installateur Zentralschweiz mit eigenen Grossbaustellen-Teams.",
 5, 4, 4, 3, "Ja", "", "https://www.ckw.ch/gebaeudetechnik/elektroinstallationen", "Firmenname (ex CKW Conex) prüfen."),
(INST, "EWS AG (Elektrizitätswerk Schwyz)", "Mehrheit CKW / Axpo", "Ibach", "SZ", "C", "DE", "ews.ch",
 "130-200 MA (uneinheitlich)", "",
 "Netzersatz, Baustrom", "Netzbetreiber mit Installationsabteilung, deckt SZ ab.",
 3, 2, 3, 3, "Ja", "", "https://ews.ch/unternehmen", ""),
(INST, "Maréchaux Elektro AG / Gruppe", "unabhängig (Familie)", "Luzern", "LU", "C", "DE", "marechaux.ch",
 "ca. 1'000 MA Gruppe, davon 750 Elektro", "",
 "Baustrom, Generator", "Grösster unabhängiger Anbieter Zentralschweiz, Grossprojekte.",
 4, 4, 3, 3, "Ja", "", "https://roi-online.ch/unternehmen/vom_elektrogeschaeft_zur_unternehmensgruppe/", ""),
(INST, "Marcel Hufschmid AG", "Burkhalter", "Zug", "ZG", "C", "DE", "hufschmid-elektro.ch",
 "ca. 100 MA", "WWZ-Unterwerk Herti geplant (Zug)",
 "USV, Generator", "Gewerbe- und Bürobauten Zug.",
 3, 2, 3, 3, "Ja", "", "https://www.hufschmid-elektro.ch/de/ueber-uns", ""),
(INST, "Elektro Compagnoni AG", "unabhängig (Familie, 2. Generation)", "Zürich", "ZH", "Z", "DE", "elektro-compagnoni.ch",
 "ca. 140 MA", "",
 "Trafo, NEA-Test, Generator", "Hochspannung, Schaltanlagen, Telecom: direkter Bedarf an Trafo-Miete und NEA.",
 5, 3, 3, 4, "Ja", "", "https://www.elektro-compagnoni.ch/", "Keine Burkhalter-Tochter."),
(INST, "EKZ Eltop AG", "EKZ", "Fahrweid (Weiningen)", "ZH", "Z", "DE", "ekzeltop.ch",
 "ca. 550 MA, ca. 40 Standorte", "",
 "Baustrom, BESS, Generator", "Flächendeckend im Kanton ZH, PV und Speicher im Portfolio.",
 5, 4, 4, 3, "Ja", "CEO Claudio Gallo (EKZ-MM 2023, Aktualität prüfen)", "https://www.moneyhouse.ch/en/company/ekz-eltop-ag-13002369831", ""),
(INST, "Baumann Koelliker Gruppe", "unabhängig (Familie)", "Zürich", "ZH", "Z", "DE", "baumann-koelliker-gruppe.ch",
 "1'250 MA, 16-17 Firmen", "",
 "Baustrom, Generator", "Viele Grossbaustellen in ZH: Baustrom-Rahmenvertrag.",
 4, 4, 4, 3, "Ja", "", "https://baumann-koelliker-gruppe.ch/", ""),
(INST, "Selmoni Gruppe", "unabhängig (prüfen)", "Münchenstein", "BL", "N", "DE", "selmoni.ch",
 "ca. 600 MA", "Life-Sciences-Projekte Basel",
 "USV, NEA-Test, Generator", "Life Sciences Basel, Verteilbau: USV, NEA, Shutdowns.",
 5, 4, 4, 3, "Ja", "", "https://smartemployer.ch/company/selmoni/", "CEO-Name nur aus Suche, nicht verifiziert."),
(INST, "Elektrotechnik AG EAGB", "Burkhalter (seit 2020)", "Basel", "BS", "N", "DE", "eagb.ch",
 "ca. 175 MA", "",
 "Generator, USV", "Basler Industrie und Spitäler: Notstrom und Überbrückung.",
 4, 3, 3, 3, "Ja", "", "https://www.eagb.ch/de/die-eag", ""),
(INST, "Jost Elektro AG Brugg", "unabhängig (Familie Bürgi)", "Brugg", "AG", "N", "DE", "jostelektro.ch",
 "ca. 200 MA", "",
 "Baustrom, NEA-Test", "Aargauer Industrie und Kraftwerksumfeld.",
 4, 3, 3, 3, "Ja", "", "https://www.aargauerzeitung.ch/aargau/kanton-aargau/bekannte-elektro-firma-im-aargau-teilt-sich-in-einzelteile-auf-ld.1822539", "Firma wurde laut AZ aufgeteilt: aktuelle Struktur prüfen."),
(INST, "Elektro-Bau AG Rothrist", "k.A.", "Rothrist", "AG", "N", "DE", "elektro-bau.ch",
 "ca. 130 MA", "",
 "Baustrom, Generator", "Logistik- und Industriebauten an der Mittelland-Achse.",
 3, 3, 3, 3, "Ja", "", "https://www.elektro-bau.ch/de/", ""),
(INST, "Alpine-Energie Schweiz AG", "ALPINE-ENERGIE Gruppe (DE/AT)", "Oftringen", "AG", "N", "DE", "",
 "k.A.", "",
 "Generator, Trafo", "Freileitung, Fahrleitung, Tunnel: mobile Energie auf Linienbaustellen.",
 5, 3, 4, 3, "Ja", "", "https://www.cylex-swiss.ch/oftringen/alpine-energie-schweiz-ag-11296004.html", "Website prüfen."),
(INST, "Hälg Group", "unabhängig (Familie)", "St. Gallen", "SG", "O", "DE", "haelg.ch",
 "1'295 MA, 30 Standorte (2025)", "",
 "Generator (Kälte/Lüftung)", "Primär HLKS, kaum Elektro. Nur Überbrückung für Kälte und Lüftung.",
 2, 3, 2, 3, "Ja", "", "https://haelg.ch/unternehmen/", ""),
(INST, "Ellenbroek Hugentobler AG", "unabhängig (prüfen)", "Frauenfeld", "TG", "O", "DE", "elhag.ch",
 ">160 MA", "",
 "Netzersatz, Generator", "Leader im Thurgau inkl. Netzbau NS/MS: Netzersatz bei Kabelzug.",
 4, 3, 3, 3, "Ja", "", "https://elhag.ch/ueber-uns/", ""),
(INST, "Wenger + Wirz AG", "unabhängig", "Schaffhausen", "SH", "O", "DE", "wenger-wirz.ch",
 "ca. 130 MA (prüfen)", "STACK-Rechenzentrum Beringen SH (36 MW, Eröffnung 2026)",
 "PQ-Audit, Baustrom, Generator", "Nr. 1 in SH, macht Netzanalysen. Nähe zum RZ-Campus Beringen.",
 4, 2, 4, 3, "Ja", "", "https://wenger-wirz.ch/ueber-uns/", "Beteiligung an STACK Beringen nicht belegt."),
(INST, "Groupe E Connect SA", "Groupe E", "Granges-Paccot / Matran", "FR", "W", "FR/DE", "groupe-e.ch",
 "880 MA, 12 Filialen FR/VD/VS/GE", "Groupe E baut 2025 rund 188 Stellen ab",
 "Baustrom, Generator", "Grossbaustellen Romandie: Baustrom, Tableaux.",
 4, 4, 3, 3, "Ja", "CEO Mutter Groupe E: Alain Sapin", "https://www.rts.ch/info/economie/2025/article/groupe-e-supprime-200-emplois-en-suisse-romande-restructuration-majeure-28856239.html", "Restrukturierung: Kostendruck."),
(INST, "Groupe E Arc SA", "Groupe E (ex Vuilliomenet)", "Boudry", "NE", "W", "FR", "groupe-e.ch",
 ">130 MA (prüfen)", "",
 "USV, Generator", "Arc jurassien: Uhrenindustrie, USV bei Unterbrüchen.",
 3, 2, 3, 3, "Ja", "", "https://www.groupe-e.ch/fr/vuilliomenet-changement-nom", ""),
(INST, "Romande Energie Services SA", "Romande Energie", "Morges (prüfen)", "VD", "W", "FR", "romande-energie.ch",
 ">200 MA", "",
 "BESS, Generator, USV", "Industrie und Tertiär VD/FR/GE/VS/NE, PV und Speicher im Portfolio.",
 4, 3, 3, 3, "Ja", "", "https://www.zonebourse.com/cours/action/ROMANDE-ENERGIE-HOLDING-S-183676/actualite/Romande-Energie-Achat-de-la-societe-HD-Energies-Sarl-26669185/", ""),
(INST, "Egg-Telsa SA", "unabhängig (prüfen)", "Genève", "GE", "W", "FR", "eggtelsa.com",
 "300 bis knapp 500 MA", "Cap2030 Genève Aéroport (2026-2032)",
 "Baustrom, Event, Generator, USV", "Grösster unabhängiger Installateur in Genf: Baustrom, Events, internationale Organisationen.",
 5, 4, 4, 3, "Ja", "", "https://www.eggtelsa.com/entreprise/", ""),
(INST, "Sedelec SA", "Burkhalter", "Carouge", "GE", "W", "FR", "sedelec-geneve.ch",
 ">200 MA", "",
 "Baustrom, USV", "Genfer Grossbaustellen, dazu Sedelec Lausanne.",
 4, 4, 4, 3, "Ja", "", "https://www.sedelec-geneve.ch/fr/a-propos-de-nous", ""),
(INST, "Mérinat SA", "Burkhalter (seit 2021)", "Vevey", "VD", "W", "FR", "merinat.ch",
 "ca. 80 MA", "Montreux Jazz Festival in der Region",
 "Generator, Event", "Riviera, Hotellerie und Kliniken: Notstrom.",
 3, 2, 4, 3, "Ja", "", "https://www.zonebourse.com/cours/action/BURKHALTER-HOLDING-AG-13303338/actualite/Burkhalter-Le-Groupe-Burkhalter-rachete-Merinat-SA-en-Suisse-romande-35769970/", ""),
(INST, "Cauderay SA", "unabhängig", "Lausanne", "VD", "W", "FR", "cauderay.com",
 "ca. 85 MA", "",
 "Baustrom, Generator", "Gewerbe und Tertiär Lausanne.",
 3, 2, 3, 3, "Ja", "", "https://www.cauderay.com/", ""),
(INST, "Grichting & Valterio Electro SA", "Burkhalter (seit 2009)", "Sion", "VS", "W", "FR/DE", "grichting-valterio.ch",
 "104-170 MA (uneinheitlich)", "Lonza Visp Ramp-up 2026",
 "Baustrom, NEA-Test, Generator", "Walliser Industrie (Lonza-Umfeld) und Infrastruktur.",
 5, 3, 4, 3, "Ja", "", "https://www.grichting-valterio.ch/fr/", ""),
(INST, "Electrasim SA", "unabhängig", "Lugano / Balerna", "TI", "T", "IT", "electrasim.ch",
 "50 MA", "",
 "USV, Generator", "Industrie-Tableaux und Automation im Tessin: USV, Shutdowns.",
 3, 2, 3, 3, "Ja", "", "https://electrasim.ch/azienda", ""),
(INST, "Elettro-Celio SA", "Burkhalter", "Giubiasco", "TI", "T", "IT", "celio.ch",
 "ca. 30 MA", "SBB-Frequenzumformer Giubiasco in Modernisierung",
 "Baustrom, Generator", "Sopraceneri und Mesolcina.",
 3, 2, 4, 3, "Ja", "", "https://ticinoaziende.ch/2025/04/09/elettro-celio-sa-di-giubiasco-eccellenza-e-innovazione-nelle-installazioni-elettriche/", ""),

# ---------------- FACILITY MANAGER ----------------
(FM, "ISS Schweiz AG", "ISS A/S", "Zürich", "ZH", "Z", "DE/FR/IT", "ch.issworld.com",
 "ca. 14'200 MA CH (2024)", "",
 "NEA-Test, USV, Generator", "Grösster IFM-Anbieter: NEA-Tests und USV-Überbrückung in tausenden Liegenschaften. Rahmenvertrag skaliert.",
 4, 5, 3, 3, "Ja", "", "https://www.moneycab.com/company/iss-schweiz/", ""),
(FM, "Apleona Schweiz AG", "Apleona", "Schaffhausen (HSG: Wallisellen)", "SH", "O", "DE/FR", "apleona.ch",
 "ca. 1'700 MA, 14 Standorte GE-SG", "",
 "NEA-Test, Generator, Trafo", "Technisches FM: Mietgeneratoren bei NEA-Revisionen und Trafo-Wartungen.",
 4, 4, 3, 3, "Nein", "", "https://apleona.ch/", ""),
(FM, "CBRE GWS GmbH", "CBRE", "Basel", "BS", "N", "DE", "cbre.ch",
 "550-1'000 MA (widersprüchlich)", "Pharmamandate Basel",
 "NEA-Test, USV, Generator", "Starke Pharma- und Industriemandate in Basel mit kritischer Stromversorgung.",
 5, 4, 4, 3, "Ja", "", "https://www.swissbau.ch/de/p/cbre-gws-schweiz.142727", ""),
(FM, "Honegger AG", "unabhängig (inkl. Cabiancardi SA, TI)", "Köniz", "BE", "M", "DE/FR/IT", "honegger.ch",
 "ca. 6'500 MA, 23 Standorte", "",
 "USV, NEA-Test", "FM für Spitäler und Reinräume: USV und Notstrom in Wartungsfenstern.",
 4, 4, 3, 3, "Ja", "", "https://honegger.ch/en/about-honegger/", ""),
(FM, "Priora FM AG", "Eiffage", "Zürich", "ZH", "Z", "DE/FR/IT", "priorafm.com",
 "ca. 650 MA", "",
 "Generator, NEA-Test", "Landesweites FM inkl. Tessin und Genf.",
 3, 3, 3, 3, "Nein", "", "https://www.priorafm.com/en/priora-fm", ""),
(FM, "Vebego AG", "Vebego", "Zürich", "ZH", "Z", "DE/FR", "vebego.ch",
 ">6'000 MA, 20 Standorte", "",
 "Generator", "Integrales FM, Schwerpunkt Reinigung. Stromersatz bei geplanten Abschaltungen.",
 3, 4, 2, 3, "Nein", "", "https://www.vebego.ch/de/ueber-uns", ""),
(FM, "Equans Switzerland Facility Management AG", "Bouygues / Equans", "Zug", "ZG", "C", "DE/FR", "equans.ch",
 "k.A.", "Fusion mit Equans Solutions Suisse SA (02/2026), neue ZN Sisseln und Kloten",
 "NEA-Test, Trafo, Generator", "Technisches FM in Industrie und Pharma (Sisseln). Neuordnung 2026: Lieferanten werden neu gewählt.",
 5, 4, 4, 3, "Ja", "", "https://www.northdata.com/Equans%20Switzerland%20Facility%20Management%20AG,%20Zug/CHE-105.849.954", ""),

# ---------------- STADTWERKE / EVU ----------------
(EVU, "ewz (Elektrizitätswerk der Stadt Zürich)", "Stadt Zürich", "Zürich", "ZH", "Z", "DE", "ewz.ch",
 "Stadtnetz Zürich", "Unterwerk-Neubauten/-Umbauten (z.B. Oerlikon)",
 "Trafo, Generator, BESS", "Unterwerksprojekte: provisorische Einspeisung per mobilem Trafo oder Generator.",
 5, 4, 4, 3, "Ja", "", "https://www.baunetzwissen.de/elektro/objekte/sonderbauten/unterwerk-und-netzstuetzpunkt-in-zuerich-4817704", "Öffentliche Beschaffung (IVöB) beachten."),
(EVU, "EKZ", "Kanton Zürich", "Dietikon", "ZH", "Z", "DE", "ekz.ch",
 "ca. 1'570 MA, 17'187 km Netz", "",
 "Trafo, Generator, BESS", "Grosses Verteilnetz mit laufender Erneuerung: Netzersatz beim Trafostations-Tausch.",
 5, 5, 3, 3, "Ja", "", "https://www.ekz.ch/de/ueber-ekz/unternehmen.html", ""),
(EVU, "Energie Wasser Bern (ewb)", "Stadt Bern", "Bern", "BE", "M", "DE", "ewb.ch",
 "ca. 780 MA", "UW Engehalde Sanierung 2022-2026",
 "Trafo, Generator", "Unterwerk-Sanierungen: mobile Trafos und Überbrückung.",
 5, 3, 4, 3, "Nein", "", "https://www.ewb.ch/", ""),
(EVU, "IWB", "Kanton Basel-Stadt", "Basel", "BS", "N", "DE", "iwb.ch",
 "ca. 1'100 GWh/a Stromabsatz", "Verstärkung Netzknoten Basel",
 "Trafo, Generator", "Bei Umschaltungen an Netzknoten Bedarf an temporärer Einspeisung.",
 5, 4, 4, 3, "Ja", "", "https://www.iwb.ch/ueber-uns/newsroom/medienmitteilungen/artikel~_IWB-verst%C3%A4rkt-wichtigsten-Knotenpunkt-des-Basler-Stromnetzes~", ""),
(EVU, "Primeo Energie", "Genossenschaft", "Münchenstein", "BL", "N", "DE/FR", "primeo-energie.ch",
 "615-652 MA, >170'000 Kunden", "",
 "Generator, BESS", "Netzbetreiber mit Energiedienstleistungen, auch als Wiederverkaufspartner denkbar.",
 4, 3, 3, 3, "Nein", "", "https://www.primeo-energie.ch/en/ueber-uns/unternehmen.html", ""),
(EVU, "SIG Services Industriels de Genève", "Kanton Genf", "Le Lignon (Vernier)", "GE", "W", "FR", "sig-ge.ch",
 "1'736 MA, 4'712 km Netz", "",
 "Generator, Trafo, BESS", "Grosses urbanes Netz mit vielen Baustellen: Notstrom für Kunden bei Netzarbeiten.",
 5, 4, 3, 3, "Ja", "", "https://www.vorbild-energie-klima.admin.ch/fr/services-industriels-de-geneve-fr", ""),
(EVU, "Romande Energie", "börsenkotiert", "Morges", "VD", "W", "FR", "romande-energie.ch",
 "1'467 MA (30.06.2025)", "",
 "BESS, Trafo, Generator", "Grösster Verteilnetzbetreiber der Romandie. Netzausbau und PV-Integration.",
 5, 4, 3, 3, "Ja", "", "https://www.zonebourse.com/actualite-bourse/romande-energie-rapport-semestriel-2025-ce7c50d3d88bf324", ""),
(EVU, "Groupe E", "Kantone FR/NE", "Granges-Paccot", "FR", "W", "FR/DE", "groupe-e.ch",
 "2'597 MA (Ende 2024)", "Stellenabbau 2025",
 "Trafo, Generator", "Netzbetreiber mit eigener Installationssparte: Netzersatz bei Umbauten.",
 4, 4, 3, 3, "Nein", "CEO Alain Sapin", "https://de.wikipedia.org/wiki/Groupe_E", ""),
(EVU, "Viteos SA", "Städte NE", "Neuchâtel", "NE", "W", "FR", "viteos.ch",
 ">320 MA", "",
 "Generator, Trafo", "Netzbetreiber. Tochter Betelec (Elektrotechnik) als zweiter Ansprechpartner.",
 3, 3, 3, 3, "Nein", "", "https://www.viteos.ch/a-propos-de-viteos/nous-connaitre/nos-activites/", ""),
(EVU, "OIKEN SA", "ex ESR + Sierre-Energie (seit 2020)", "Sion", "VS", "W", "FR", "oiken.ch",
 ">470 MA, ca. 150'000 Kunden", "",
 "Generator, Trafo", "Grösster EVU im Wallis. Bergregion mit Netzbau, mobile Einspeisung bei Leitungsarbeiten.",
 4, 3, 3, 3, "Nein", "", "https://oiken.ch/entreprise/notre-histoire/", ""),
(EVU, "CKW", "Axpo", "Rathausen (Emmen)", "LU", "C", "DE", "ckw.ch",
 "ca. 2'200 MA, ca. 2'500 Trafostationen", "",
 "Trafo, Generator, BESS", "Viele Trafostationen im Erneuerungszyklus: mobile Trafos. Zugang auch über CKW Gebäudetechnik.",
 5, 5, 4, 3, "Ja", "", "https://www.ckw.ch/ueber-ckw/unternehmen", ""),
(EVU, "WWZ", "börsenkotiert", "Zug", "ZG", "C", "DE", "wwz.ch",
 ">470 MA, 2'200 km Netz", "Unterwerk Herti geplant",
 "Trafo, BESS, Generator", "Unterwerk-Neubau: temporäre Einspeisung und BESS.",
 4, 3, 4, 3, "Nein", "", "https://www.wwz.ch/-/media/ueber-wwz/wwz-gruppe/geschichte/factsheet-kurzportrait.pdf", ""),
(EVU, "SAK", "Kantone SG/AR/AI", "St. Gallen", "SG", "O", "DE", "sak.ch",
 "ca. 460-480 MA", "Übernahme Fremdnetze (z.B. Marthy Energie)",
 "Netzersatz, BESS, Generator", "Hat Installation und Grossbatteriespeicher. Netzintegration braucht mobilen Netzersatz.",
 4, 3, 3, 3, "Nein", "", "https://www.sak.ch/ueber-sak/unternehmen", ""),
(EVU, "Repower AG", "börsenkotiert", "Poschiavo", "GR", "O", "DE/IT", "repower.com",
 "747 MA (Ende 2025), ca. 3'000 km Netz", "",
 "Trafo, Generator", "Unterwerke und Trafostationen in abgelegenen Tälern: mobile Trafos und Generatoren bei Revisionen.",
 4, 3, 3, 3, "Nein", "", "https://www.repower.com/ch/medienmitteilungen/jahresergebnis-2025", ""),
(EVU, "AIL SA (Aziende Industriali di Lugano)", "Stadt Lugano", "Muzzano", "TI", "T", "IT", "ail.ch",
 ">430 MA, >110'000 Kunden", "",
 "Generator, Event, Trafo", "Grösster Verteiler im Tessin: Netzersatz bei Bauarbeiten und Events in Lugano.",
 4, 3, 3, 3, "Ja", "", "https://www.ail.ch/AIL/chi-siamo.html", ""),
(EVU, "AET (Azienda Elettrica Ticinese)", "Kanton Tessin", "Monte Carasso (Bellinzona)", "TI", "T", "IT", "aet.ch",
 ">400 km MS/HS-Netz", "Unterwerk-Projekt mit Swissgrid in Biasca",
 "Trafo, Generator", "Temporäre Versorgung während Unterwerk-Umbauten.",
 4, 3, 4, 3, "Nein", "", "https://www.aet.ch/it/infrastruttura-di-rete", ""),

# ---------------- ELEKTROPLANER ----------------
(PLAN, "Amstein + Walthert", "unabhängig", "Zürich", "ZH", "Z", "DE/FR", "amstein-walthert.ch",
 ">1'100 MA, 10 Standorte", "",
 "Spezifikation NEA/USV/BESS, PQ-Audit", "Führender Gebäudetechnikplaner: legt Notstrom und USV in Ausschreibungen für Spitäler und RZ fest.",
 5, 4, 4, 3, "Ja", "", "https://amstein-walthert.ch/en/", "Planer kauft nicht selbst: Ziel ist Nennung in Ausschreibungen."),
(PLAN, "Basler & Hofmann", "unabhängig", "Esslingen", "ZH", "Z", "DE", "baslerhofmann.ch",
 "ca. 530 MA in CH", "",
 "Spezifikation BESS, PQ-Audit", "Kompetenzzentrum Erneuerbare inkl. Speicher: BESS-Spezifikation.",
 4, 3, 3, 3, "Nein", "", "https://www.baslerhofmann.ch/en", ""),
(PLAN, "AFRY Schweiz AG", "AFRY (ex Pöyry)", "Zürich", "ZH", "Z", "DE/FR/IT", "afry.com",
 ">1'000 MA CH, 20 Standorte", "",
 "Spezifikation Trafo/Generator", "Energie- und Netzplaner (Kraftwerke, UW): Bauprogramme mit temporärer Einspeisung.",
 4, 4, 3, 3, "Nein", "", "https://afry.com/en/offices/switzerland", ""),
(PLAN, "Gruner AG", "unabhängig", "Basel", "BS", "N", "DE", "gruner.ch",
 ">1'100 MA (international)", "",
 "Spezifikation NEA/USV", "Gebäudetechnik und Energieanlagen, Planung von Notstromkonzepten.",
 4, 3, 3, 3, "Nein", "", "https://www.gruner.ch/en", ""),
(PLAN, "HHM Gruppe (Hefti. Hess. Martignoni.)", "unabhängig", "Aarau", "AG", "N", "DE", "hhm.ch",
 ">280 MA", "",
 "Spezifikation NEA/USV, PQ-Audit", "Reiner Elektroplaner mit Kompetenzfeld Energie: schreibt NEA und USV aus.",
 5, 3, 4, 3, "Ja", "", "https://www.hhm.ch/hhmgruppe", ""),
(PLAN, "HKG Engineering AG (Herzog Kull Group)", "unabhängig", "Baden (ab 01.03.2026)", "AG", "N", "DE/FR", "hkg.ch",
 "ca. 180 MA, 12 Standorte", "Neuer Firmensitz Baden 2026",
 "Spezifikation Provisorien", "Elektroplanung und Gebäudeautomation: Provisorien bei Umbauten.",
 4, 3, 3, 3, "Nein", "", "https://www.aargau.swiss/news/herzog-kull-group-bezieht-neuen-firmensitz-in-baden/", ""),
(PLAN, "IBG Engineering AG", "unabhängig", "Winterthur", "ZH", "O", "DE", "ibg.ch",
 "k.A., Standorte SG, Chur, Weinfelden u.a.", "",
 "Spezifikation NEA", "Elektroplanung Stark- und Schwachstrom, Energietechnik. Stark in der Ostschweiz.",
 4, 2, 3, 3, "Nein", "", "https://www.ibg.ch/gebaude/angebot/elektroplanung", ""),
(PLAN, "SCHERLER AG (Ingenieurbüro)", "unabhängig", "Luzern", "LU", "C", "DE", "scherler.swiss",
 ">200 MA", "",
 "Spezifikation NEA/USV/Mittelspannung, PQ-Audit", "Planer für NEA, USV und Mittelspannung: Einfluss auf Ausschreibungen.",
 5, 3, 4, 3, "Ja", "", "https://www.scherler.swiss/it/", "Nicht verwechseln mit Scherler AG Bern (Installateur)."),
(PLAN, "Weinmann-Energies SA", "unabhängig", "Echallens", "VD", "W", "FR", "weinmann-energies.ch",
 ">100 MA, Filialen GE/NE", "",
 "Spezifikation NEA/USV", "CVSE-Ingenieure Romandie: Notstrom und USV in Bau und Industrie.",
 4, 3, 3, 3, "Nein", "", "https://www.weinmann-energies.ch/bureau", ""),
(PLAN, "SRG Engineering", "unabhängig", "Le Mont-sur-Lausanne", "VD", "W", "FR", "srg-engineering.ch",
 "k.A., Büros VD/GE/FR", "",
 "Spezifikation Sicherheitsstrom", "CVSE-Planer, Elektroteil inkl. Sicherheitsstrom.",
 3, 2, 3, 3, "Nein", "", "https://www.srg-engineering.ch/", "Website nicht abrufbar gewesen."),
(PLAN, "MORE Engineering SA", "k.A.", "Tessin (Ort prüfen)", "TI", "T", "IT", "moreengineering.ch",
 "k.A.", "",
 "Spezifikation NEA", "Elektro- und Energieplaner im Tessin.",
 3, 2, 3, 2, "Nein", "", "https://moreengineering.ch/", "Existenz und Grösse vor Ansprache prüfen."),
(PLAN, "Studio d'ingegneria Visani Rusconi Talleri (VRT) SA", "unabhängig", "Taverne", "TI", "T", "IT", "vrt.ch",
 "k.A., Standorte Taverne, Losone", "EOC-Spitalprojekte Tessin",
 "Spezifikation Notstrom", "Planer für Spitäler und Energiezentralen im Tessin (HLK-Schwerpunkt).",
 3, 2, 3, 3, "Nein", "", "https://www.vrt.ch/chi-siamo", ""),

# ---------------- GU / TU ----------------
(GU, "Implenia", "börsenkotiert", "Lupfig, Dielsdorf, Sisikon, Zürich", "ZH", "Z", "DE/FR", "implenia.com",
 "Grösster Baukonzern CH", "GU Green-RZ Lupfig und Dielsdorf; Sisikoner Tunnel (ARGE, 2025-2034); Hagenholztunnel SBB",
 "Baustrom, Lastbank/NEA-Test, Generator, Trafo", "RZ-Bau mit Commissioning plus Tunnelbaustrom über Jahre. Höchster Hebel in der Liste.",
 5, 5, 5, 3, "Ja", "", "https://implenia.com/medien/artikel/implenia-gewinnt-attraktive-neue-projekte-in-den-bereichen-datacenter-gesundheit-sowie-energie-und-verkehrsinfrastruktur/", ""),
(GU, "Frutiger AG", "unabhängig", "Thun", "BE", "M", "DE", "frutiger.com",
 "k.A.", "Sisikoner Tunnel (ARGE); Neubau Bernstrasse 11 Thun (bis 2027)",
 "Generator, Trafo, Baustrom", "Aggregate für Tunnelvortrieb und Lüftung, Baustrom im Hochbau.",
 5, 4, 5, 3, "Nein", "", "https://www.frutiger.com/de/unternehmen/news", ""),
(GU, "Marti-Gruppe", "unabhängig", "Moosseedorf / Airolo", "BE", "T", "DE/IT", "marti.com",
 "k.A.", "2. Gotthardröhre, Hauptlos Süd (ca. 7,8 km TBM)",
 "Trafo, Generator, Redundanz", "Redundante Versorgung für TBM und Tunnellüftung, mobile Trafos.",
 5, 5, 4, 3, "Ja", "", "https://www.marti.com/ch_en/stories/messages/2024-07-31_Zweite-Gotthardroehre-Umfangreiche-Arbeiten-Nachhaltigkeit.php", "Region nach Baustelle (Airolo) gesetzt, HQ Moosseedorf BE."),
(GU, "Losinger Marazzi", "Bouygues", "Genève / Vernier", "GE", "W", "FR", "losinger-marazzi.ch",
 "k.A.", "Konsortium LMB: neues Terminal GVA (Cap2030, ca. 600 Mio., 2026-2032)",
 "Baustrom, Generator, Überbrückung", "Baustrom im laufenden Flughafenbetrieb, Überbrückung bei Netzumschaltungen.",
 5, 5, 4, 3, "Ja", "", "https://gva.blog/le-projet-cap2030-en-neuf-questions/", ""),
(GU, "HRS Real Estate", "unabhängig", "Frauenfeld", "TG", "O", "DE", "hrs.ch",
 "k.A.", "Hochhaus «Chez Fritz» Frauenfeld (2026-2029)",
 "Baustrom, BESS", "TU mit Grossbaustellen in der ganzen Schweiz.",
 4, 4, 3, 3, "Nein", "", "https://www.hrs.ch/de/projekte/chez-fritz-hochhaus", ""),
(GU, "ERNE Gruppe", "unabhängig", "Laufenburg", "AG", "N", "DE", "erne-gruppe.ch",
 "k.A.", "Bauunternehmer FlexBase Laufenburg (BESS plus KI-RZ, ca. 1 Mrd.)",
 "Baustrom, Generator, Lastbank", "Grossaushub ca. 400'000 m³, danach NEA- und Testlastbedarf.",
 5, 4, 5, 3, "Ja", "", "https://www.erne-gruppe.ch/en/projects/new-flexbase-technology-center-laufenburg/", ""),
(GU, "Anliker AG", "unabhängig", "Emmenbrücke", "LU", "C", "DE", "anliker.ch",
 "k.A.", "Rohbau USZ Campus MITTE1|2; Forum UZH (Spatenstich 22.09.2026)",
 "Baustrom, Generator", "Baustrom im Spitalumfeld mit hohem Anspruch an Versorgungssicherheit.",
 4, 3, 4, 3, "Nein", "", "https://www.anliker.ch/aktuelles/2025/universitatsspital-zurich---neubau-campus-mitte1-2-fur-hochklassige-medizin", ""),
(GU, "Halter AG", "unabhängig", "Schlieren", "ZH", "Z", "DE/FR", "halter.ch",
 "k.A., Filialen BE/BS/Lausanne/Genf", "AuPark Wädenswil Etappe 2 (03/2026)",
 "Baustrom, BESS", "TU für Grossareale: BESS für emissionsarme Wohnbaustellen.",
 4, 3, 3, 3, "Nein", "", "https://www.halter.ch/de/projekte/aupark", ""),
(GU, "Walo Bertschinger", "unabhängig", "Dietikon", "ZH", "Z", "DE/FR", "walo.ch",
 "k.A.", "Zwei N16-Brücken Péry für ASTRA (bis Ende 2026)",
 "Generator, BESS", "Linienbaustellen Strassen- und Tiefbau: mobile Generatoren.",
 4, 3, 4, 3, "Nein", "", "https://www.zhk.ch/de/wirtschaft-und-politik/news/walo-bertschinger-realisiert-zwei-neue-bruecken-im-kanton-bern.html", ""),
(GU, "Induni & Cie SA", "unabhängig", "Genève", "GE", "W", "FR", "induni.ch",
 "k.A.", "Baustellen En Sauvy/Lancy, Hauts de Vandoeuvres",
 "Baustrom, Generator", "Baustrom im urbanen Genf.",
 3, 3, 3, 3, "Nein", "", "https://induni.ch/actualites/", ""),
(GU, "Mancini & Marti SA", "unabhängig", "Tessin", "TI", "T", "IT", "mancinimarti.ch",
 "k.A.", "",
 "Baustrom", "Traditionsbauer im Tessin, kein konkretes Projekt verifiziert.",
 3, 2, 2, 3, "Nein", "", "https://www.mancinimarti.ch/it/chi-siamo/", "Projektlage prüfen."),

# ---------------- RECHENZENTREN ----------------
(RZ, "Green Datacenter", "green.ch", "Lupfig / Dielsdorf", "AG", "N", "DE", "green.ch",
 "Lupfig 12 MW", "Lupfig: Start 2026; Dielsdorf: Baustart RZ 3 für 2026 geplant",
 "Lastbank/NEA-Test, Generator, USV", "Jedes neue RZ braucht Commissioning-Lastbanktests und Inbetriebnahmestrom.",
 5, 5, 5, 3, "Ja", "", "https://www.baublatt.ch/bauprojekte/green-baut-viertes-rechenzentrum-auf-metro-campus-in-dielsdorf-zh-36395", ""),
(RZ, "Digital Realty (ex Interxion)", "Digital Realty", "Glattbrugg", "ZH", "Z", "EN/DE", "digitalrealty.com",
 "Campus ZUR1-4, danach ca. 60 MW", "Spatenstich ZUR4 26.08.2026: 15 MW, Eröffnung 2028",
 "Baustrom, Lastbank/NEA-Test", "Neubau mit Commissioning 2027/28. Früh in Spezifikation kommen.",
 5, 5, 5, 3, "Ja", "", "https://www.inside-it.ch/spatenstich-fuer-neues-rz-von-digital-reality-in-glattbrugg-20260827", "Sprache: Englisch klären."),
(RZ, "Vantage Data Centers", "Vantage", "Winterthur / Glattfelden", "ZH", "Z", "EN", "vantage-dc.com",
 "ZRH2 Glattfelden 24 MW (>370 Mio.)", "ZRH12 im Bau (Rohbau 10/2025); ZRH2 Glattfelden",
 "Lastbank, Generator, Überbrückung", "Load-Bank-Tests und temporäre Versorgung bis zum Netzanschluss.",
 5, 5, 4, 2, "Ja", "", "https://vantage-dc.com/data-center-locations/emea/zurich-ii-switzerland/", "Beschaffung oft zentral (EMEA)."),
(RZ, "NTT Global Data Centers", "NTT", "Rümlang", "ZH", "Z", "EN/DE", "services.global.ntt",
 "bis 20 MW", "",
 "NEA-Test, USV", "Wiederkehrende NEA- und USV-Tests, Überbrückung bei Retrofits.",
 4, 3, 2, 3, "Nein", "", "https://www.datacentermap.com/switzerland/zurich/e-shelter-zurich/", ""),
(RZ, "Equinix", "Equinix", "Zürich / Genf", "ZH", "Z", "EN/DE", "equinix.ch",
 "ZH2/ZH4/ZH5, GV1/GV2", "Ausbau Zürcher RZ für 40 Mio. (11/2024)",
 "NEA-Test, Überbrückung", "NEA-Tests und temporäre Versorgung bei Erweiterungen.",
 4, 4, 3, 2, "Nein", "", "https://www.inside-it.ch/equinix-baut-data-center-in-zuerich-aus-20241112", ""),
(RZ, "STACK Infrastructure", "STACK", "Beringen", "SH", "O", "EN/DE", "stackinfra.com",
 "36 MW Hyperscale", "Beringen: Eröffnung 2026 geplant, eigenes Unterwerk",
 "Überbrückung, Lastbank, Generator", "Verzögert sich das Unterwerk, braucht es Überbrückung. Commissioning-Lastbank sicher.",
 5, 5, 5, 2, "Ja", "", "https://www.stackinfra.com/about/news-press/news/new-data-center-campus-in-beringen-switzerland/", ""),
(RZ, "Vaultica (ex Safe Host / STACK Genf)", "Apollo (Verkauf 2025)", "Plan-les-Ouates", "GE", "W", "FR/EN", "",
 "GEN01/GEN02", "Namenswechsel, neuer Eigentümer 2025",
 "NEA-Test, USV", "Neuer Betreiber: Service-Verträge werden neu vergeben.",
 4, 3, 4, 3, "Nein", "", "https://www.datacentermap.com/switzerland/geneva/stack-infrastructure-gen01/", "Name und Website prüfen."),
(RZ, "Infomaniak", "unabhängig", "Genève", "GE", "W", "FR", "infomaniak.com",
 "RZ D4", "D4 seit 01/2025, bei 25 % Auslastung, Vollausbau bis 2028",
 "Lastbank, USV", "Stufenweiser Ausbau mit wiederkehrendem Commissioning-Bedarf. Schweizer Firma, kurze Wege.",
 4, 3, 4, 4, "Nein", "", "https://www.ictjournal.ch/articles/2025-01-27/infomaniak-inaugure-un-datacenter-qui-recycle-toute-la-chaleur-quil-produit", ""),
(RZ, "NorthC Datacenters", "NorthC", "Arlesheim / Genf / Winterthur", "BL", "N", "DE/FR/EN", "northcdatacenters.com",
 "3 Standorte CH", "Arlesheim bis Mitte 2027; Genf Baustart Q1 2026",
 "Baustrom, Lastbank/NEA-Test", "Zwei laufende RZ-Baustellen gleichzeitig (NWCH und West).",
 5, 4, 5, 3, "Ja", "", "https://www.northcdatacenters.com/de/pressemitteilungen/northc-baut-auf-dem-campus-uptownbasel-das-rechenzentrum-der-zukunft/", ""),
(RZ, "Swisscom (Rechenzentren)", "Swisscom", "Bern-Wankdorf", "BE", "M", "DE", "swisscom.ch",
 "k.A.", "Neubau-RZ ca. 100 Mio. als Ersatz Zentweg (Datum prüfen)",
 "Überbrückung, NEA-Test", "Migrations-Überbrückung und NEA-Tests. Zugang evtl. über cablex.",
 4, 4, 3, 2, "Nein", "", "https://www.kleinreport.ch/news/swisscom-baut-neues-rechenzentrum-in-bern-wankdorf-70850/", "Projektstand prüfen."),
(RZ, "FlexBase Group", "unabhängig", "Laufenburg", "AG", "N", "DE/EN", "flexbase.ch",
 "BESS >1,6 GWh / 800 MW plus KI-RZ", "Bau seit Frühling 2025, IBN Sommer 2028 (Zeitplan umstritten)",
 "Baustrom, Lastbank, BESS-Know-how", "Grösstes BESS-Projekt der Schweiz. BESS-Kompetenz von MiT als Türöffner.",
 5, 5, 4, 2, "Ja", "", "https://flexbase.ch/en/project-overview", "Finanzierung und Zeitplan kritisch beobachten."),
(RZ, "CSCS (ETH Zürich)", "ETH", "Lugano-Cornaredo", "TI", "T", "IT/EN", "cscs.ch",
 "Supercomputer «Alps»", "",
 "USV, NEA-Test", "USV- und NEA-Wartungsfenster eines HPC-Centers.",
 4, 2, 2, 3, "Nein", "", "https://www.cscs.ch/publications/news/2012/cscs-moves-into-new-computer-centre-in-lugano/", "Öffentliche Beschaffung."),

# ---------------- INDUSTRIE ----------------
(IND, "Roche", "Roche Holding", "Basel / Kaiseraugst", "BS", "N", "DE/EN", "roche.ch",
 "ca. 1,4 Mrd. in laufenden Bauprojekten", "Bau 12 (500 Mio., bis 2029); Synthetic Molecules Facility (790 Mio.)",
 "Baustrom, USV, Generator, Trafo", "Baustrom und Überbrückung bei GMP-Umschaltungen. Enorme Ausfallkosten.",
 5, 5, 4, 2, "Ja", "", "https://www.roche.ch/medien-schweiz/informationen/med-ch-2025-10-29", "Einkauf zentral, Zugang oft über Installateur/FM."),
(IND, "Novartis", "Novartis", "Stein / Schweizerhalle", "AG", "N", "DE/EN", "novartis.com",
 "k.A.", "11/2025: 80 Mio. USD siRNA Schweizerhalle, 26 Mio. USD Steril Stein; Abbau 550 Stellen Stein bis 2027",
 "Überbrückung, USV", "Temporäre Versorgung bei Werksumbau und Anlagenumstellungen.",
 4, 4, 3, 2, "Nein", "", "https://www.novartis.com/ch-de/news/media-releases/novartis-passt-produktionsaktivitaeten-der-schweiz-und-investiert-innovative-herstelltechnologien", ""),
(IND, "Lonza", "Lonza Group", "Visp", "VS", "W", "DE/EN", "lonza.com",
 "k.A.", "Grosse Säugerzell-Anlage Ibex: volle Produktion ab Mitte 2026",
 "USV, NEA-Test, Generator", "USV- und NEA-Redundanz bei Qualifizierung und Ramp-up.",
 5, 4, 4, 2, "Ja", "", "https://www.pharmamanufacturing.com/sector/contract-manufacturing/article/55378861/lonzas-large-scale-mammalian-site-in-visp-switzerland-continues-ramp-up-process", "Oberwallis: deutschsprachig."),
(IND, "Bachem", "börsenkotiert", "Bubendorf / Sisslerfeld", "BL", "N", "DE", "bachem.com",
 "k.A.", "Bau K (ca. 550 Mio.) Ramp-up 2026; Werk Sisslerfeld (750 Mio., bis ca. 2030)",
 "Baustrom, Überbrückung, Generator", "Greenfield-Baustelle Sisslerfeld über Jahre plus Ramp-up in Bubendorf.",
 5, 4, 5, 3, "Ja", "", "https://www.bachem.com/articles/news/company-news/bachem-expands-presence-in-northwestern-switzerland-new-production-site-planned-in-sisslerfeld/", ""),
(IND, "Siegfried", "börsenkotiert", "Zofingen", "AG", "N", "DE", "siegfried.ch",
 "Investitionen 2025: 211,9 Mio.", "Ausbau Zofingen (Steril, Fill & Finish)",
 "Überbrückung, USV", "Temporäre Versorgung bei Erweiterungen im laufenden Betrieb.",
 4, 3, 3, 3, "Nein", "", "https://www.siegfried.ch/app/uploads/2026/02/Siegfried_2025_GB_Lagebericht-und-Strategiebericht_DE.pdf", ""),
(IND, "Thermo Fisher (Werk CSL Behring Lengnau)", "Thermo Fisher", "Lengnau", "BE", "M", "DE/EN", "thermofisher.com",
 "k.A.", "",
 "USV, NEA-Test", "USV- und NEA-Tests in einer Biologika-Anlage.",
 4, 3, 2, 3, "Nein", "", "https://www.nzz.ch/wirtschaft/in-der-neuen-biotech-fabrik-in-lengnau-uebernimmt-thermo-fisher-das-zepter-ld.1558484", ""),
(IND, "Syngenta", "Syngenta Group", "Monthey", "VS", "W", "FR", "syngenta.ch",
 "k.A.", "CO2-Reduktionsplan bis 2030",
 "Überbrückung", "Überbrückung bei Energieumbau und Revisionen am Chemiestandort.",
 3, 3, 2, 3, "Nein", "", "https://www.scienceindustries.ch/fr/article/40697/syngenta-a-monthey-un-avenir-durable", ""),
(IND, "Emmi", "börsenkotiert", "Suhr / Emmen / Ostermundigen", "AG", "N", "DE", "emmi.com",
 "k.A.", "Neue PET-Anlage Suhr (27 Mio.) seit 09/2026",
 "Generator", "Kühlkette absichern: Notstrom bei Netzarbeiten.",
 3, 2, 2, 3, "Nein", "", "https://packaging-journal.de/emmi-nimmt-neue-pet-anlage-in-suhr-in-betrieb/", ""),
(IND, "Stahl Gerlafingen", "AFV Beltrame", "Gerlafingen", "SO", "M", "DE", "stahl-gerlafingen.com",
 "k.A.", "Staatshilfe 2025-2028, eine Linie 2024 stillgelegt",
 "Trafo (MS)", "Starker Spardruck. Höchstens MS-Trafo-Miete bei Revisionen.",
 2, 3, 2, 2, "Nein", "", "https://www.neo1.ch/artikel/staatliche-unterstuetzung-fuer-stahl-gerlafingen-rollt-an", "Bonität prüfen."),
(IND, "Swiss Steel / Steeltec", "Swiss Steel Group", "Emmenbrücke", "LU", "C", "DE", "swisssteel-group.com",
 "k.A.", "Abbau 130 von 750 Stellen; EU-Safeguard ab 01.07.2026",
 "Trafo", "Tiefe Priorität, allenfalls mobile Trafos bei Revisionen.",
 2, 3, 2, 2, "Nein", "", "https://www.watson.ch/schweiz/wirtschaft/831341707-swiss-steel-bleibt-beim-abbau-von-130-stellen-in-emmenbruecke", "Bonität prüfen."),

# ---------------- SPITÄLER ----------------
(SPI, "Universitätsspital Zürich (USZ)", "Kanton Zürich", "Zürich", "ZH", "Z", "DE", "usz.ch",
 "k.A.", "Campus MITTE1|2: Gebäudetechnik ab 2026, fertig 2031",
 "Überbrückung, NEA-Test, USV", "Umschaltungen im laufenden Spitalbetrieb über mehrere Jahre.",
 5, 4, 4, 2, "Nein", "", "https://www.usz.ch/grundsteinlegung-fuer-das-spital-der-zukunft-ein-meilenstein-fuer-das-usz/", "Öffentliche Beschaffung."),
(SPI, "Insel Gruppe", "Kanton Bern", "Bern", "BE", "M", "DE", "inselgruppe.ch",
 "k.A.", "Forschungs- und Ausbildungszentrum (435 Mio.) im Bau",
 "NEA-Test, Überbrückung", "Notstrom-Redundanz bei Inbetriebnahmen und Umzügen.",
 4, 3, 4, 2, "Nein", "", "https://inselgruppe.ch/de/die-insel-gruppe/bauprojekte", ""),
(SPI, "HUG (Hôpitaux Universitaires de Genève)", "Kanton Genf", "Genève", "GE", "W", "FR", "hug.ch",
 "k.A.", "Beau-Séjour 22-24 eröffnet 06/2026, Spital Beau-Séjour in Renovation",
 "Generator, NEA-Test", "Temporäre NEA während Renovation und Umschaltung.",
 4, 3, 4, 2, "Nein", "", "https://www.hug.ch/construction-batiment-beau-sejour-22-24", ""),
(SPI, "CHUV", "Kanton Waadt", "Lausanne", "VD", "W", "FR", "chuv.ch",
 "k.A.", "Esplanade bis Ende 2026",
 "Generator, NEA-Test", "Temporäre NEA bei Umbauten.",
 4, 3, 3, 2, "Nein", "", "https://www.medinside.ch/fr/chuv-une-nouvelle-esplanade-dici-fin-2026-20260217", ""),
(SPI, "EOC (Ente Ospedaliero Cantonale)", "Kanton Tessin", "Lugano / Bellinzona", "TI", "T", "IT", "eoc.ch",
 "k.A.", "Umbau Civico Lugano (200 Mio. über 10 Jahre); Neubau Bellinzona in Planung",
 "Überbrückung, NEA-Test", "Notstrom-Überbrückung beim Umbau im laufenden Betrieb.",
 4, 3, 4, 3, "Nein", "", "https://www.eoc.ch/media-e-news/news/2025/CS-ampliamento-civico.html", ""),

# ---------------- INFRASTRUKTUR ----------------
(INF, "Flughafen Zürich AG", "börsenkotiert", "Kloten", "ZH", "Z", "DE", "flughafen-zuerich.ch",
 "k.A.", "Dock A: Planauflage 2026, Tower-Bau ab 2027, Dock ab 2030",
 "Baustrom, Überbrückung", "Jetzt positionieren für Bau ab 2027.",
 4, 4, 3, 2, "Nein", "", "https://www.flughafen-zuerich.ch/en/company/flughafen-zuerich/airport-development/current-construction-projects/main-airport-complex-development", ""),
(INF, "Genève Aéroport", "Kanton Genf", "Cointrin", "GE", "W", "FR", "gva.ch",
 "k.A.", "Cap2030: multimodale Plattform 2026-2029, Terminal ab 2027",
 "Überbrückung, Generator", "Umbau unter Betrieb (mit Losinger Marazzi).",
 5, 4, 4, 2, "Nein", "", "https://gva.blog/le-projet-cap2030-en-neuf-questions/", ""),
(INF, "SBB Energie", "SBB", "Rupperswil / Kerzers / Giubiasco", "AG", "N", "DE/FR/IT", "sbb.ch",
 "k.A.", "Modernisierung Frequenzumformer Rupperswil bis 2026, weitere in Giubiasco und Mendrisio",
 "Trafo, Generator", "Mobile Trafos und Generatoren für Hilfsbetriebe während Umbauten.",
 5, 4, 4, 2, "Ja", "", "https://company.sbb.ch/de/ueber-die-sbb/projekte/projekte-mittelland-tessin/frequenzumformerwerk-rupperswil.html", "Öffentliche Beschaffung."),

# ---------------- EVENTS ----------------
(EVT, "Montreux Jazz Festival", "Stiftung", "Montreux", "VD", "W", "FR", "montreuxjazzfestival.com",
 "16 Tage", "60. Ausgabe 03.-18.07.2026",
 "Event, Hybrid (BESS + Generator)", "Hybrid-Event-Strom für Bühnen und Gastro. Planung 2027 beginnt im Winter.",
 5, 3, 4, 3, "Nein", "", "https://www.montreuxjazzfestival.com/en/news/programme-2026/", ""),
(EVT, "Paléo Festival Nyon", "Verein", "Nyon", "VD", "W", "FR", "paleo.ch",
 "6 Tage", "21.-26.07.2026",
 "Event, Hybrid (BESS + Generator)", "Grosses Openair auf der grünen Wiese.",
 5, 3, 4, 3, "Nein", "", "https://www.jambase.com/festival/paleo-festival-2026", ""),
(EVT, "OpenAir St.Gallen", "k.A.", "St. Gallen (Sittertobel)", "SG", "O", "DE", "openairsg.ch",
 "ca. 30'000 Besucher/Tag, 6 Bühnen", "25.-28.06.2026",
 "Event, Generator, BESS", "Netzferner Standort: grosser Generator- und BESS-Bedarf.",
 5, 4, 4, 3, "Nein", "", "https://www.openairsg.ch/", ""),
(EVT, "Street Parade", "Verein", "Zürich", "ZH", "Z", "DE", "streetparade.com",
 "30 Love Mobiles", "08.08.2026",
 "Event, Generator", "Event-Strom für Stages und Infrastruktur.",
 4, 3, 4, 3, "Nein", "", "https://www.zvv.ch/de/freizeit-und-events/freizeittipps/events/street-parade.html", ""),
(EVT, "Lauberhornrennen", "Verein", "Wengen", "BE", "M", "DE", "lauberhorn.ch",
 "k.A.", "97. Austragung 15.-17.01.2027",
 "Generator (Winter), Event", "TV-Produktion und Zielgelände. BKW ist Sponsor: Konkurrenzlage prüfen.",
 4, 3, 4, 2, "Nein", "", "https://www.lauberhorn.ch/rennen/", ""),
(EVT, "Moon&Stars Locarno", "k.A.", "Locarno", "TI", "T", "IT", "moonandstars.ch",
 "11 Tage", "09.-19.07.2026",
 "Event, Hybrid", "Piazza Grande: zusammen mit Filmfestival fast ein Monat am selben Platz.",
 4, 3, 4, 3, "Nein", "", "https://www.ticino.ch/en/events/details/moon-stars-2026/10053.html", ""),
(EVT, "Locarno Film Festival", "Verein", "Locarno", "TI", "T", "IT", "locarnofestival.ch",
 "11 Tage", "05.-15.08.2026",
 "Event, Hybrid", "Direkt nach Moon&Stars am gleichen Platz: Paketangebot möglich.",
 4, 3, 4, 3, "Nein", "", "https://www.ascona-locarno.com/en/events/details/locarno-film-festival-2026/10056", ""),
]

# Kernliste GU/TU/Industrie-Gruppe (14): Implenia, Marti, Losinger, ERNE, Green, Digital Realty, Vantage,
# STACK, NorthC, FlexBase, Roche, Lonza, Bachem, SBB Energie
