# -*- coding: utf-8 -*-
"""Datenbasis Top-Player Power Schweiz 2027 (Recherche Stand 27.09.2026).

Szenario je Projekt (alles Annahmen, in der Excel änderbar):
  gen_mva, gen_wo   Generator-Leistung in MVA und Mietdauer in Wochen
  lb_mw, lb_wo      Lastbank in MW und Mietdauer in Wochen
  bess_mw, bess_mo  Batteriespeicher in MW und Mietdauer in Monaten
  anteil27          Anteil des Volumens, der ins Jahr 2027 fällt
  p                 Wahrscheinlichkeit, dass MiT den Auftrag gewinnt
"""

RZ, INF, NETZ, SPI, IND, EVT, KAN = ("Rechenzentrum", "Infrastruktur", "Netz / Unterwerk", "Spital",
                                     "Industrie", "Event", "Kanal-Partner")

# Marktrichtwerte (Annahmen-Blatt). Quelle je Wert, Umrechnung mit FX und cos phi im Excel.
RATES = dict(
    fx=0.828,           # USD/CHF 24.09.2026
    cosphi=0.8,
    gen_usd_lo=5000, gen_usd_hi=7800,      # USD pro MW und Woche (500-kW-Klasse x2, US-Richtwert)
    lb_usd_lo=1600, lb_usd_hi=3100,        # USD pro MW und Woche (1-MW-Lastbank, US-Richtwert)
    bess_usd_lo=10000, bess_usd_hi=50000,  # USD pro MW und Monat (Herstellerblog, Bandbreite)
    diesel_lh=145, diesel_chf=2.41,
    cool_usd_month=34666, cool_mw=1.75,
)


def rate_gen(r=RATES):
    return (r["gen_usd_lo"] + r["gen_usd_hi"]) / 2 * r["cosphi"] * r["fx"]


def rate_lb(r=RATES):
    return (r["lb_usd_lo"] + r["lb_usd_hi"]) / 2 * r["fx"]


def rate_bess(r=RATES):
    return (r["bess_usd_lo"] + r["bess_usd_hi"]) / 2 * r["fx"]


# (segment, projekt, einstieg, ort, kt, region, sprache, anlass, bedarf,
#  gen_mva, gen_wo, lb_mw, lb_wo, bess_mw, bess_mo, anteil27, p, crosssell, schritt, quelle, hinweis)
P = [
# ---------------------------------------------------------------- Rechenzentren
(RZ, "STACK ZUR02 Beringen", "STACK Infrastructure; PM MBA Projektmanagement", "Beringen", "SH", "Ostschweiz", "EN/DE",
 "36 MW IT, Betriebsstart Herbst 2026, neues Unterwerk vom Betreiber finanziert",
 "Lastbank für IST je Data Hall, Generator-Überbrückung falls Unterwerk verzögert, Tankcontainer",
 4, 8, 12, 3, 0, 0, 0.6, 0.30, "Temporäre Kühlung beim IST, falls Kälte nicht fertig",
 "Commissioning-Manager STACK und MBA sofort anfragen: IST-Plan der nächsten Phasen",
 "https://www.stackinfra.com/about/news-press/news/new-data-center-campus-in-beringen-switzerland/",
 "Hot Lead. Phase 1 läuft evtl. schon, Ziel sind Folgephasen 2027."),
(RZ, "Green Zürich West 4 Lupfig", "Green; GU Implenia", "Lupfig", "AG", "Nordwestschweiz", "DE",
 "12 MW IT, Inbetriebnahme 2026 geplant (eine Quelle nennt 2027)",
 "Lastbank für IST, Generator für Tests und Überbrückung",
 2, 4, 6, 4, 0, 0, 0.5, 0.30, "Temporäre Kühlung beim IST",
 "Green Facility/Commissioning und Implenia-Projektleitung kontaktieren",
 "https://implenia.com/medien/artikel/implenia-gewinnt-attraktive-neue-projekte-in-den-bereichen-datacenter-gesundheit-sowie-energie-und-verkehrsinfrastruktur/",
 "Commissioning läuft vermutlich jetzt. Tempo zählt."),
(RZ, "Green Metro-Campus Dielsdorf (nächstes RZ)", "Green; PM MBA Projektmanagement", "Dielsdorf", "ZH", "Zürich", "DE",
 "Baustart weiteres RZ 2026, Campus-Anschluss 50 MW über neues EKZ-UW",
 "Baustrom-Generator, später Lastbank für IST (2028)",
 1, 26, 6, 4, 0, 0, 0.6, 0.25, "Bauheizung und Bautrocknung im Winter",
 "Mit dem Lupfig-Kontakt bei Green gleich mitverhandeln",
 "https://www.baublatt.ch/bauprojekte/green-baut-viertes-rechenzentrum-auf-metro-campus-in-dielsdorf-zh-36395", ""),
(RZ, "Digital Realty ZUR4 Glattbrugg", "Digital Realty (GU noch unbekannt)", "Opfikon-Glattbrugg", "ZH", "Zürich", "EN",
 "15 MW IT, Spatenstich 27.08.2026, Fertigstellung 2028, High-Density/KI",
 "Baustrom 2027, Lastbank für IST 2028 (≈ IT-Last)",
 1, 26, 15, 4, 0, 0, 0.45, 0.20, "Bauheizung Winter 2026/27, Kühlung beim IST",
 "GU/Elektro über Baugesuch und simap ermitteln, dann Baustrom offerieren",
 "https://www.inside-it.ch/spatenstich-fuer-neues-rz-von-digital-reality-in-glattbrugg-20260827",
 "Deck auf Englisch klären."),
(RZ, "Vantage ZRH3 Volketswil", "Vantage Data Centers", "Volketswil", "ZH", "Zürich", "EN",
 "100 bis 150 MW Campus, Phase 1 live 2028, neue Unterwerke nötig, Engpass im Vornetz",
 "Generator/BESS-Überbrückung bis Netzanschluss, später Lastbank-IST",
 5, 26, 0, 0, 1, 6, 0.4, 0.10, "Temporäre Kühlung, Abwärme-Thema mit Energie 360°",
 "Beziehung jetzt aufbauen, Beschaffung oft EMEA-zentral",
 "https://www.datacenterdynamics.com/",
 "Grösstes Einzelpotenzial, tiefe Wahrscheinlichkeit. Quellen: EKZ blue (2025), DCD, Energie 360°; genauen Artikel-Link ergänzen."),
(RZ, "NorthC Arlesheim (uptownBasel)", "NorthC Datacenters", "Arlesheim", "BL", "Nordwestschweiz", "DE/EN",
 "4,5 MW IT (Ausbau 7,5), Betrieb ab Mitte 2027, NEA mit HVO",
 "Lastbank für IST, Generator für Tests",
 1, 12, 4.5, 3, 0, 0, 1.0, 0.30, "HVO-Generatoren passen zum Nachhaltigkeitskonzept",
 "NorthC Projektleitung CH: IST-Termin 2027 und Lastbank-Bedarf klären",
 "https://www.northcdatacenters.com/de/pressemitteilungen/northc-baut-auf-dem-campus-uptownbasel-das-rechenzentrum-der-zukunft/", ""),
(RZ, "NorthC Genf «The Hive»", "NorthC Datacenters", "Kanton Genf", "GE", "West (Romandie)", "FR/EN",
 "4,5 MW IT (3 × 1,5 MW), Baustart Q1 2026, fertig Q2 2028",
 "Baustrom, Lastbank je 1,5-MW-Stufe",
 0.5, 40, 1.5, 3, 0, 0, 0.6, 0.25, "Bauheizung, später Kühlung beim IST",
 "Zusammen mit Arlesheim als Paket anbieten",
 "https://www.northcdatacenters.com/en/press-releases/northc-group-to-build-new-high-tech-data-center-in-geneva-switzerland/", ""),
(RZ, "FlexBase Technologiezentrum Laufenburg", "FlexBase; Bau ERNE Gruppe", "Laufenburg", "AG", "Nordwestschweiz", "DE/EN",
 "KI-RZ plus Redox-Flow-Speicher >800 MW, Vollbetrieb Sommer 2028 (Zeitplan umstritten)",
 "Baustrom über Jahre, später Commissioning",
 2, 26, 0, 0, 0, 0, 0.6, 0.10, "Bauheizung, Bautrocknung",
 "Über ERNE einsteigen, Finanzierung beobachten",
 "https://flexbase.ch/en/project-overview", "Bewilligt ist nur die Gebäudehülle."),
# ---------------------------------------------------------------- Infrastruktur
(INF, "2. Gotthardröhre", "ASTRA; Marti-Gruppe (Hauptlos Süd)", "Göschenen / Airolo", "UR/TI", "Tessin", "DE/IT",
 "CHF 2,14 Mrd., Vortrieb bis ca. 2029/30",
 "Backup-Generatoren für Vortrieb und Lüftung, Lastspitzen",
 2, 52, 0, 0, 0, 0, 1.0, 0.15, "Bauheizung Portalinstallationen",
 "Marti Baustellenleitung Airolo: Backup-Konzept und Wartungsfenster",
 "https://www.astra.admin.ch/astra/de/home/themen/nationalstrassen/baustellen/medienmitteilungen/bellinzona/statolavorigottardo.html", ""),
(INF, "Sisikoner Tunnel (Neue Axenstrasse)", "ARGE Implenia/Frutiger; Bauherr ASTRA", "Sisikon", "UR", "Zentralschweiz", "DE",
 "über CHF 430 Mio., Bau Okt. 2025 bis 2034",
 "Baustrom und Netzersatz für Lüftung",
 1.5, 52, 0, 0, 0, 0, 1.0, 0.20, "Bauheizung, Entfeuchtung im Tunnel",
 "ARGE-Bauleitung: Rahmen für Baustrom-Backup",
 "https://implenia.com/medien/artikel/implenia-erhaelt-zuschlag-fuer-sisikoner-tunnel-herzstueck-der-neuen-axenstrasse-in-der-innerschweiz/", ""),
(INF, "Brüttener Tunnel (MehrSpur Zürich-Winterthur)", "SBB", "Bassersdorf / Dietlikon", "ZH", "Zürich", "DE",
 "Hauptarbeiten ab 2027, TBM ab 2029",
 "Installationsplätze vor Netzanschluss: Baustrom",
 1, 26, 0, 0, 0, 0, 1.0, 0.15, "Bauheizung",
 "SBB Infrastruktur Projekte: Baustrom-Ausschreibung verfolgen (simap)",
 "https://www.tagesanzeiger.ch/bruettener-tunnel-baustart-2026-in-bassersdorf-und-dietlikon-747315398294", "Öffentliche Beschaffung."),
(INF, "Bahnhof Zürich Stadelhofen (4. Gleis)", "SBB", "Zürich", "ZH", "Zürich", "DE",
 "CHF 1,1 Mrd., Baustart 2027, ca. 10 Jahre",
 "Leise BESS für Nachtarbeit, Netzersatz",
 0.5, 26, 0, 0, 0.5, 6, 1.0, 0.15, "Bautrocknung",
 "BESS-Hybrid als leise Lösung für Innenstadt positionieren",
 "https://www.nzz.ch/zuerich/grossprojekt-stadelhofen-was-der-bahnhofsumbau-bedeutet-ld.1884585", "Öffentliche Beschaffung."),
(INF, "Gare de Lausanne (Léman 2030)", "SBB/CFF", "Lausanne", "VD", "West (Romandie)", "FR",
 "Hauptarbeiten ab Ende 2027, viele Nachtschichten",
 "BESS und Generator für Nachtbaustellen",
 0.5, 8, 0, 0, 0.5, 3, 0.3, 0.15, "Bautrocknung",
 "CFF Projektleitung Lausanne, Dokumente auf Französisch",
 "https://company.sbb.ch/fr/developpement-ferroviaire/projets/suisse-romande-valais/leman-2030/nos-projets/gare-lausanne.html", ""),
(INF, "A1 Wankdorf-Schönbühl (8-Spur-Ausbau)", "ASTRA", "Bern / Schönbühl", "BE", "Mittelland/Bern", "DE",
 "CHF 474 Mio., ab 2027, ca. 6 Jahre",
 "Generatoren für Lichtsignale, Beleuchtung, Installationsplätze",
 0.5, 26, 0, 0, 0, 0, 1.0, 0.15, "",
 "Zuschlag an Bau-ARGE abwarten, dann ARGE ansprechen",
 "https://www.srf.ch/news/ausbau-autobahn-a1-zwischen-schoenbuehl-und-wankdorf-gibt-es-mehr-fahrspuren", ""),
(INF, "Stadtautobahn St.Gallen (BSA-Umstellung)", "ASTRA", "St. Gallen", "SG", "Ostschweiz", "DE",
 "ca. CHF 524 Mio., Schlussarbeiten 2027 bis Sommer 2028",
 "Netzersatz für Lüftung und Beleuchtung bei Umstellung",
 1, 12, 0, 0, 0, 0, 1.0, 0.20, "",
 "ASTRA Filiale Winterthur / BSA-Unternehmer: Umschaltplan",
 "https://stadtautobahn.ch/zahlen-fakten/", ""),
(INF, "Flughafen Zürich: neuer Tower", "Flughafen Zürich AG", "Kloten", "ZH", "Zürich", "DE",
 "Tower-Bau ab 2027 (ca. 2 Jahre), Dock A ab 2030 (> CHF 1 Mrd.)",
 "Netzersatz und BESS bei Umschaltungen im 24/7-Betrieb",
 1, 12, 0, 0, 0.5, 6, 0.5, 0.15, "Klima/Kühlung für Provisorien",
 "Flughafen Energie/Technik: Rahmen für Umschaltungen anbieten",
 "https://www.flughafen-zuerich.ch/en/company/flughafen-zuerich/airport-development/current-construction-projects/main-airport-complex-development", ""),
(INF, "Genève Aéroport Cap2030 / Plateforme multimodale", "Genève Aéroport; Losinger Marazzi (LMB)", "Genf", "GE", "West (Romandie)", "FR",
 "ca. CHF 560 bis 640 Mio., Multimodal 2026-2029, Terminal ab 2027",
 "Baustrom und USV/BESS im laufenden Terminalbetrieb",
 1, 26, 0, 0, 0.5, 6, 0.6, 0.15, "Bauheizung, Klima Provisorien",
 "Losinger Marazzi Bauleitung GVA, Französisch",
 "https://gva.blog/les-futurs-grands-chantiers-de-geneve-aeroport-dici-2033/", ""),
(INF, "Pumpspeicherwerk Grimsel 4", "KWO (BKW-Beteiligung)", "Grimsel", "BE", "Mittelland/Bern", "DE",
 "CHF 300 Mio., 2 × 84 MW, Bau Juni 2026 bis 2032",
 "Baustrom und Backup für hochalpine Untertagebaustelle",
 1, 52, 0, 0, 0, 0, 1.0, 0.15, "Bauheizung, Entfeuchtung",
 "KWO Projektleitung: Backup-Konzept Kaverne",
 "https://www.grimselstrom.ch/projekte/pumpspeicherwerk-grimsel-4", "BKW-Nähe: Konkurrenzlage prüfen."),
# ---------------------------------------------------------------- Netz
(NETZ, "Axpo UW Niederurnen (Gesamterneuerung)", "Axpo Grid", "Niederurnen", "GL", "Ostschweiz", "DE",
 "110/16 kV, ab Frühling 2026 ca. 3 Jahre, etappenweise",
 "Netzersatz und Eigenbedarf bei Umschaltungen, mobiler Trafo (Wert fehlt)",
 2, 8, 0, 0, 0, 0, 1.0, 0.25, "",
 "Axpo Grid Projektleitung: Etappenplan 2027",
 "https://www.axpo.com/ch/de/newsroom/medienmitteilungen/2026/gesamterneuerung-des-unterwerks-niederurnen-im-kanton-glarus---a.html",
 "Trafo-Miete nicht eingerechnet."),
(NETZ, "ewz UW Sihlfeld (Erneuerung)", "ewz", "Zürich", "ZH", "Zürich", "DE",
 "Innerstädtisches Unterwerk, 2027-2029",
 "Provisorien: Generator-Netzersatz, mobiler Trafo (Wert fehlt)",
 2, 8, 0, 0, 0, 0, 0.5, 0.20, "",
 "ewz Netzbau: Provisoriumskonzept, IVöB-Verfahren beachten",
 "https://www.stadt-zuerich.ch/de/aktuell/medienmitteilungen/2026/03/ewz-unterwerk-sihlfeld-wird-erneuert.html", "Öffentliche Beschaffung."),
(NETZ, "CKW: UW Sursee und Trafostations-Erneuerung", "CKW", "Sursee / Zentralschweiz", "LU", "Zentralschweiz", "DE",
 "UW Sursee IBN Frühling 2027 (CHF 11 Mio.), ca. 2'500 Trafostationen im Netz",
 "Netzersatz bei Umschaltungen, Generatoren für Trafostations-Tausch",
 1, 18, 0, 0, 0, 0, 1.0, 0.25, "",
 "CKW Netzbau: Rahmen für Netzersatz beim Stationstausch",
 "https://www.luzernerzeitung.ch/zentralschweiz/kanton-luzern/stromnetz-ckw-investiert-11-millionen-franken-in-unterwerk-sursee-ld.2761224",
 "Szenario: UW Sursee 2 MVA × 4 Wo plus Stationstausch 0,5 MVA × 20 Wo = ca. 18 MVA-Wochen."),
(NETZ, "Swissgrid UW Innertkirchen (neue GIS)", "Swissgrid", "Innertkirchen", "BE", "Mittelland/Bern", "DE",
 "ca. CHF 33 Mio., Baustart frühestens 2027",
 "Eigenbedarf und Provisorien während Umschaltung",
 1, 12, 0, 0, 0, 0, 0.3, 0.15, "",
 "Swissgrid Projektleitung, Ausschreibung verfolgen",
 "https://www.plattformj.ch/artikel/164567/", ""),
(NETZ, "Romande Energie: UW-Modernisierung HS/MS", "Romande Energie", "Kanton Waadt", "VD", "West (Romandie)", "FR",
 "Mehrere Unterwerk-Umbauten 2024-2027",
 "Netzersatz, mobiler Trafo (Wert fehlt)",
 1, 12, 0, 0, 0, 0, 1.0, 0.20, "",
 "Romande Energie Netzbau, Französisch",
 "https://www.pme.ch/conseils-dexperts/romande-energie/moderniser-les-postes-electriques-haute-et-moyenne-tension-pour-relever-les-defis/y3npfj2", ""),
# ---------------------------------------------------------------- Spitäler
(SPI, "Kantonsspital Aarau «Dreiklang»", "KSA; TU Implenia", "Aarau", "AG", "Nordwestschweiz", "DE",
 "ca. CHF 750 Mio., Übergabe 15.09.2026, Umzug Jan. 2027, danach Rückbau",
 "NEA-Lasttest mit Lastbank, Netzersatz beim Umzug, Baustrom Rückbau",
 1, 34, 2, 2, 0, 0, 1.0, 0.25, "Klima/Kühlung während Umzug",
 "KSA Technik und Implenia: NEA-Test und Rückbau-Baustrom jetzt anbieten",
 "https://www.ksa.ch/de/kantonsspital-aarau/ueber-uns/die-bauprojekte/neubau-dreiklang", ""),
(SPI, "USZ Campus MITTE1|2", "USZ; b+p baurealisation", "Zürich", "ZH", "Zürich", "DE",
 "CHF 950 Mio., Bau laufend, Betrieb 2031",
 "Netzersatz und BESS bei Umschaltungen im Vollbetrieb",
 1, 12, 0, 0, 0.5, 6, 1.0, 0.15, "Klima/Kühlung Provisorien",
 "USZ Technik: Umschaltkonzept 2027",
 "https://www.usz.ch/standorte/usz-campus/campusmitte/", "Öffentliche Beschaffung."),
(SPI, "Kantonsspital St.Gallen Haus 07B", "HOCH Health Ostschweiz", "St. Gallen", "SG", "Ostschweiz", "DE",
 "Rohbau 2026, Ausbau 2027/28, Übergabe 2029",
 "Baustrom Ausbau, später NEA-Test",
 0.5, 26, 0, 0, 0, 0, 1.0, 0.15, "Bauheizung, Trocknung",
 "HOCH Bau und Technik: Ausbauphase 2027",
 "https://www.kssg.ch/immobilien-und-betrieb/bauprojekte/neubauprojekt-come-together/neubau-haus-07b", ""),
# ---------------------------------------------------------------- Industrie
(IND, "Bachem Werk Sisslerfeld", "Bachem", "Eiken", "AG", "Nordwestschweiz", "DE",
 "über CHF 500 Mio., Greenfield, Bau bis ca. 2030",
 "Baustrom bis Netzanschluss, später Qualifizierung",
 1, 40, 0, 0, 0, 0, 1.0, 0.20, "Bauheizung, Bautrocknung",
 "Bachem Engineering und GU: Baustromkonzept",
 "https://www.bachem.com/wp-content/uploads/2026/07/2026-07-21-Press-Release-BSF-FINAL-DE.pdf", ""),
(IND, "Roche Basel Bau 51 und laufende Bauten", "Roche", "Basel / Kaiseraugst", "BS", "Nordwestschweiz", "DE/EN",
 "Bau 51 CHF 790 Mio. (Grundstein 21.09.2026), ca. CHF 1,4 Mrd. laufende Bauten",
 "Baustrom, später Lastbank/USV bei Qualifizierung",
 1, 26, 0, 0, 0, 0, 1.0, 0.15, "Klima/Reinraum-Provisorien",
 "Zugang über Installateur/FM vor Ort (ETAVIS K+S, Selmoni, CBRE)",
 "https://www.baublatt.ch/bauprojekte/roche-legt-grundstein-fuer-neuen-produktionsbau-in-basel-39630", ""),
(IND, "Lonza Stein Fill & Finish (plus Visp)", "Lonza", "Stein / Visp", "AG/VS", "Nordwestschweiz", "DE/EN",
 "CHF 500 Mio. Anlage Stein operativ ab H1 2027, Ibex Visp im Ramp-up",
 "NEA-Lasttests, temporäre USV, Netzersatz bei Validierung",
 1, 12, 2, 2, 0, 0, 1.0, 0.20, "Kühlung bei Validierung",
 "Lonza Engineering Stein: Inbetriebnahme H1 2027",
 "https://www.bioprocessintl.com/facilities-capacity/lonza-expands-stein-site-again-with-commercial-fill-finish-plant", ""),
(IND, "Novartis Schweizerhalle und Stein", "Novartis", "Pratteln / Stein", "BL/AG", "Nordwestschweiz", "DE/EN",
 "USD 80 Mio. siRNA Schweizerhalle, USD 26 Mio. Sterile Stein, bis ca. 2028",
 "Netzersatz bei Umbauten im GMP-Betrieb",
 1, 12, 0, 0, 0, 0, 1.0, 0.15, "Klima",
 "Novartis Engineering: Umschaltfenster",
 "https://www.novartis.com/ch-de/news/media-releases/novartis-passt-produktionsaktivitaeten-der-schweiz-und-investiert-innovative-herstelltechnologien", ""),
# ---------------------------------------------------------------- Events
(EVT, "WEF Annual Meeting 2027", "World Economic Forum", "Davos", "GR", "Ostschweiz", "EN/DE",
 "18.-22.01.2027, Pavillons und Sicherheit bei knappem Ortsnetz",
 "Generatoren redundant, BESS-Hybrid für leise Zonen",
 4, 3, 0, 0, 1, 1, 1.0, 0.15, "Zeltheizung, Heizzentralen (MiT-Kern)",
 "Offerte für 2027 jetzt, Aufbau startet im Dezember",
 "https://www.davos.ch/en/experience/events/world-economic-forum-annual-meeting-2027", "Szenario-Grösse ist Annahme."),
(EVT, "FIS Ski-WM Crans-Montana 2027", "Swiss-Ski / OK Crans-Montana 2027", "Crans-Montana", "VS", "West (Romandie)", "FR",
 "01.-14.02.2027, zwei Wochen Broadcast, Fan-Zonen, Hospitality",
 "Redundante Generatoren (n+1), BESS für Hospitality",
 3, 4, 0, 0, 0.5, 1, 1.0, 0.20, "Zeltheizung, Heizzentralen",
 "OK Crans-Montana 2027 sofort kontaktieren, Französisch",
 "https://www.cransmontana2027.ch/en/", "Szenario-Grösse ist Annahme."),
(EVT, "ESAF 2028 Thun", "OK ESAF 2028", "Thun", "BE", "Mittelland/Bern", "DE",
 "25.-27.08.2028, Aufbau ab Frühsommer 2028",
 "Arena, Festgelände, Camping: Generatoren und BESS",
 4, 4, 0, 0, 1, 1, 0.0, 0.20, "Kühlung Gastro",
 "Offerte und Konzept 2027, Umsatz 2028",
 "https://www.esaf2028.ch/", "Umsatz fällt 2028 an."),
# ---------------------------------------------------------------- Kanal-Partner
(KAN, "Burkhalter Gruppe (Rahmen)", "Burkhalter Holding, 83 Gesellschaften", "Zürich", "ZH", "Zürich", "DE/FR/IT",
 "5'356 FTE, 169 Standorte (31.12.2025)",
 "Baustrom und NEA-Tests über viele Töchter",
 1, 30, 0, 0, 0, 0, 1.0, 0.20, "Bauheizung, Trocknung über dieselben Baustellen",
 "Zentraler Einkauf: Rahmenvertrag, dann Töchter regional",
 "https://ch.marketscreener.com/boerse-nachrichten/burkhalter-kurzversion-nichtfinanzielle-berichterstattung-2025-ce7e50ded98bf423",
 "Rahmenvolumen (MVA-Wochen) ist Annahme."),
(KAN, "ETAVIS / VINCI Energies (Rahmen)", "VINCI Energies: ETAVIS, Actemium, Gfeller", "Zürich", "ZH", "Zürich", "DE/FR/IT",
 ">2'400 MA ETAVIS; Infrastruktur, RZ, Industrie",
 "Baustrom, Lastbank bei Inbetriebnahmen",
 1, 30, 1, 6, 0, 0, 1.0, 0.20, "Bauheizung",
 "VINCI Einkauf CH: Rahmen für Power",
 "https://www.vinci-energies.ch/unsere-bereiche/etavis/", "Rahmenvolumen ist Annahme."),
(KAN, "Equans Switzerland (Rahmen)", "Bouygues / Equans", "Zürich", "ZH", "Zürich", "DE/FR",
 ">1'600 MA, Energie, Verkehr, Industrie, FM",
 "Netzersatz, NEA-Tests, Baustrom",
 1, 25, 1, 4, 0, 0, 1.0, 0.20, "Heizung/Kühlung im FM-Geschäft",
 "Equans Einkauf und FM-Leitung gemeinsam",
 "https://www.phase5.ch/nun-heisst-es-offiziell-equans-switzerland", "Rahmenvolumen ist Annahme."),
(KAN, "BKW Building Solutions (Rahmen)", "BKW: AEK, ISP, swisspro, Arnold, inelectro", "Ostermundigen", "BE", "Mittelland/Bern", "DE/FR",
 "ca. 4'000 MA in ca. 50 Firmen",
 "Baustrom, Netzersatz (Arnold: Kabelnetzbau)",
 1, 20, 0, 0, 0, 0, 1.0, 0.15, "Bauheizung",
 "BKW BS Einkauf; BKW ist auch Energie-Anbieter",
 "https://www.bkw.com/en/about-us/building-solutions", "Rahmenvolumen ist Annahme."),
(KAN, "CKW Gebäudetechnik und EKZ Eltop (Rahmen)", "Axpo-Gruppe (CKW) / EKZ", "Luzern / Zürich", "LU/ZH", "Zentralschweiz", "DE",
 "ca. 1'400 MA CKW GT, ca. 550 MA EKZ Eltop",
 "Baustrom, BESS",
 1, 20, 0, 0, 0, 0, 1.0, 0.15, "Bauheizung",
 "Getrennt ansprechen, gemeinsam auswerten",
 "https://www.ckw.ch/gebaeudetechnik/elektroinstallationen", "Rahmenvolumen ist Annahme."),
]

# Beobachten: unter CHF 50'000 oder zu unsicher (segment, name, ort, grund, quelle)
W = [
(RZ, "Equinix ZH4 Phase 6", "Zürich", "CHF 40 Mio. Ausbau, fertig 2027. Kleiner Commissioning-Umfang.", "https://www.inside-it.ch/equinix-baut-data-center-in-zuerich-aus-20241112"),
(RZ, "ENKA Rechenzentrum Beringerfeld", "Beringen SH", "Baugesuch in Vorprüfung, starker Widerstand.", "https://www.shn.ch/"),
(RZ, "Microsoft / AWS / Google Cloud-Regionen", "Zürich / Genf", "Standorte nicht öffentlich, meist Colocation: Zugang über Green, Vantage, STACK.", "https://news.microsoft.com/de-ch/"),
(RZ, "Swiss Government Cloud (BIT)", "Bund", "CHF 319 Mio. 2025-2032, Private Cloud in eigenen RZ.", "https://www.bit.admin.ch/"),
(NETZ, "Alpiq BESS Niedergösgen 300 MW / 1,2 GWh", "Niedergösgen SO", "Bau 2027, IBN 2029: Baustrom klein, Partner-Thema BESS.", "https://www.ess-news.com/"),
(NETZ, "BESS Bonaduz 60 MW / 120 MWh", "Bonaduz GR", "COD H1 2027, Commissioning-Support prüfen.", "https://www.energy-storage.news/"),
(SPI, "Spital Sion Erweiterung", "Sion VS", "OP-Bündelung bis Ende 2027, Umfang eher unter CHF 50'000.", "https://www.lenouvelliste.ch/"),
(IND, "Swiss Chip FabLab Dübendorf", "Dübendorf ZH", "Finanzierung offen, Betrieb ab 2028 geplant.", "https://www.itmagazine.ch/artikel/85232/"),
(EVT, "Weltcup Adelboden und Lauberhorn", "Adelboden / Wengen BE", "Je unter CHF 50'000 Miete, zusammen interessant. BKW Sponsor Lauberhorn.", "https://www.lauberhorn.ch/en/races/"),
(EVT, "Sommer-Openairs (St.Gallen, Frauenfeld, Gurten, Paléo, Montreux)", "diverse", "Einzeln meist unter CHF 50'000, als Saisonpaket prüfen.", "https://www.openairsg.ch/"),
(EVT, "Art Basel 2027", "Basel", "Satelliten-Pavillons, Umfang unklar.", "https://www.basel.com/en/events/art-basel"),
(INF, "Zimmerberg-Basistunnel II", "Thalwil-Baar", "Bau ab 2029.", "https://company.sbb.ch/"),
(INF, "Stadion Hardturm Zürich", "Zürich", "Baubeginn frühestens 2027/28.", "https://www.20min.ch/"),
("Facility Manager", "ISS, CBRE, Honegger (NEA-Test-Programme)", "national", "Wiederkehrende NEA-Tests, je Objekt klein: als Rahmen prüfen.", "https://ch.issworld.com/"),
("Elektroplaner", "Amstein + Walthert, HHM, Scherler", "national", "Kaufen nicht selbst, schreiben aber Notstrom und Lastbank-Tests aus.", "https://amstein-walthert.ch/"),
]

COMP = [
("Avesco Rent (Cat)", "Cat-Generatoren, z.B. XQP500 (550 kVA)", "https://www.avescorent.ch/de/mietkategorie/power-system/"),
("Bimex", "Aggregate bis 2'000 kVA, netzparallel", "https://www.bimex.ch/mieten/"),
("GENGA AG", "bis 670 kVA, auf Anfrage bis 2'500 kVA", "https://www.genga.ch/"),
("Kummler+Matter EVT", "Mobile Trafostationen MS/NS (Partner und Wettbewerber)", "https://kuma-evt.ch/de/kompetenzen/energie/energieversorgung/bauprovisorien-mittel-niederspannung"),
("Arag Bau", "Generatoren 20 bis 608 kVA", "https://www.arag-bau.ch/"),
("Loxam CH / Boels CH", "Generatoren bis ca. 150 kVA", "https://www.loxam.ch/"),
("Energyst (Cat Rental Power)", "Generatoren, Trafos, Lastbänke; CH vermutlich über Avesco", "https://www.energyst.com/solutions/"),
]

# ---------------------------------------------------------------- gemeinsam für Excel und Deck
ZIELROLLE = {
    RZ: "Commissioning-Manager, Construction Manager, Critical Facility Ops",
    INF: "Bauleitung ARGE, Baustelleneinrichtung, Einkauf",
    NETZ: "Leiter Netzbau / Unterwerke, Projektleiter UW",
    SPI: "Leiter Technik und Betrieb, TU-Projektleitung",
    IND: "Engineering / Utilities, Technischer Einkauf",
    EVT: "Produktionsleitung, Technische Leitung OK",
    KAN: "Einkauf Gruppe, Bereichsleiter Grossprojekte",
}

# Produktbedarf je Segment: 3 Kernbedarf, 2 häufig, 1 gelegentlich, 0 kaum (Einschätzung aus den Szenarien)
PRODUKTE = ["Generator", "Lastbank", "BESS", "Mobiler Trafo", "NEA-Test / USV", "Tank / HVO"]
MATRIX = {
    RZ: [3, 3, 2, 1, 3, 2],
    INF: [3, 0, 2, 1, 0, 3],
    NETZ: [3, 0, 1, 3, 1, 1],
    SPI: [2, 2, 2, 1, 3, 1],
    IND: [3, 1, 1, 1, 2, 1],
    EVT: [3, 0, 3, 0, 0, 2],
    KAN: [3, 1, 1, 1, 2, 1],
}

PORTFOLIO = [  # Produkt, Wofür, Typische Kunden, Kennwerte / Hinweis, Quelle
    ("Generator", "Baustrom, Netzersatz, Events, Überbrückung bis Netzanschluss",
     "GU/TU, Tunnel, RZ im Bau, Events, Netzbetreiber",
     "Aggreko CH: 30 bis 2'100 kVA, Diesel, Gas, HVO, Stage V. Immer klären: Prime (Dauer) oder Standby (Notstrom).",
     "aggreko.com/de-ch/products/generators"),
    ("Lastbank", "Künstliche Last für NEA-Tests und RZ-Commissioning (IST)",
     "RZ, Spitäler, Pharma, Facility Manager",
     "Aggreko: 100 bis 6'250 kW, Commissioning Level L1 bis L5, flüssigkeitsgekühlte Varianten für KI-RZ.",
     "aggreko.com (Data Centre Commissioning, Load Banks)"),
    ("BESS", "Leise, emissionsfreie Versorgung, Lastspitzen kappen, Hybrid mit Generator",
     "Events, Nachtbaustellen, Innenstadt, Spitäler",
     "Beispiel Aggreko: 1 MW / 1,2 MWh. Immer nutzbare Kapazität (kWh) und C-Rate angeben, nicht Nennkapazität.",
     "aggreko.com"),
    ("Mobiler Trafo", "Provisorische Einspeisung MS/NS bei Unterwerk- und Stationsumbau",
     "Netzbetreiber, Industrie, Grossbaustellen",
     "Bei MiT nicht belegt, über Aggreko prüfen. Mietsatz: Wert fehlt, aus Preisliste ergänzen.",
     "aggreko.com"),
    ("NEA-Test und Messung", "Netzersatzanlage unter Last prüfen, Netzqualität vor und nach Umschaltung messen",
     "Spitäler, Industrie, RZ, Facility Manager",
     "Messung nach EN 50160 (Spannungsmerkmale) mit Geräten nach IEC 61000-4-30 Klasse A.",
     "eigene Fachkompetenz"),
    ("Tankcontainer / HVO", "Treibstoff-Logistik für Dauerbetrieb, erneuerbarer Diesel",
     "Tunnel, RZ-Überbrückung, Events",
     "1 MVA bei 75 % Last: ca. 139 bis 154 l/h (Cummins C1000 D5), rund CHF 350 pro Stunde bei 2,41 CHF/l.",
     "Cummins-Datenblatt; TCS 18.09.2026"),
    ("Cross-Sell Wärme / Kälte", "Bauheizung, Trocknung, temporäre Kühlung, Zeltheizung, Entfeuchtung",
     "Winterbaustellen, RZ-IST, Spital-Umzug, WEF, Ski-WM",
     "MiT-Kerngeschäft. Kühlung Richtwert ca. CHF 16'400 pro MW (therm.) und Monat (US-Lease, umgerechnet).",
     "mobilintime.com; kwipped.com"),
]

RZ_DETAIL = [  # Betreiber/Projekt, Standort, IT-MW, Zeitplan, GU/PM, Netzanschluss, Status für uns, Quelle
    ("STACK ZUR02", "Beringen SH", "36", "Aufrichte 2025, Betriebsstart Herbst 2026", "PM MBA Projektmanagement",
     "neues Unterwerk vom Betreiber finanziert, ca. 350 GWh/a", "Hot Lead: Folgephasen-IST 2027", "stackinfra.com; shn.ch 12.02.2026"),
    ("Green Zürich West 4", "Lupfig AG", "12", "Baustart 01/2025, IBN 2026 (eine Quelle: 2027)", "GU Implenia (> CHF 150 Mio.)",
     "Abwärme ins Netz IBB", "Hot Lead: Commissioning läuft", "implenia.com 27.03.2025"),
    ("Green Metro-Campus", "Dielsdorf ZH", "Campus-Anschluss 50 MW", "RZ2/RZ3 im Bau, weiteres RZ Baustart 2026", "PM MBA Projektmanagement",
     "EKZ-UW Dielsdorf (CHF 14 Mio., 50 MW) seit 09/2025", "Baustrom 2027, IST 2028", "baublatt.ch; ekz.ch"),
    ("Digital Realty ZUR4", "Opfikon-Glattbrugg ZH", "15", "Spatenstich 27.08.2026, fertig 2028", "unbekannt: simap / Baugesuch prüfen",
     "unbekannt", "Baustrom 2027, IST 2028", "investor.digitalrealty.com 27.08.2026"),
    ("Vantage ZRH3", "Volketswil ZH", "100 bis 150", "Phase 1 live 2028", "unbekannt",
     "neue Unterwerke nötig, Engpass Vornetz Axpo/Swissgrid", "Beziehung aufbauen, EMEA-Beschaffung", "ekz.ch/blue 2025; datacenterdynamics.com"),
    ("NorthC Arlesheim", "Arlesheim BL", "4,5 (Ausbau 7,5)", "Betrieb ab Mitte 2027", "unbekannt",
     "6 MVA, NEA mit HVO", "IST 2027", "northcdatacenters.com 11.09.2025"),
    ("NorthC «The Hive»", "Kanton Genf", "4,5 (3 × 1,5)", "Baustart Q1 2026, fertig Q2 2028", "unbekannt",
     "NEA mit HVO, Direct-to-Chip", "Baustrom 2027, IST 2028", "northcdatacenters.com"),
    ("FlexBase TZL", "Laufenburg AG", "bis ca. 500 (technisch, ?)", "Spatenstich 05.05.2025, Vollbetrieb Sommer 2028 (umstritten)", "ERNE Gruppe",
     "Swissgrid Phase 1 bewilligt, 800 MW", "Beobachten, über ERNE", "flexbase.ch; srf.ch"),
    ("Equinix ZH4 Phase 6", "Zürich", "?", "CHF 40 Mio., fertig 2027", "?", "?", "Beobachten (unter CHF 50'000)", "inside-it.ch 12.11.2024"),
    ("NTT Zurich 1", "Rümlang ZH", "20", "in Betrieb, keine Erweiterung gefunden", "–", "–", "NEA-Tests wiederkehrend", "datacentermap.com"),
    ("ENKA Beringerfeld", "Beringen SH", "?", "Baugesuch in Vorprüfung, Widerstand", "ENKA İnşaat", "unklar", "Beobachten", "shaz.ch 10.08.2026"),
]

PLAN = [  # Monat, Termin, Aufgabe, Projekt
    ("Oktober", "16.10.2026", "Commissioning-Manager kontaktieren, IST-Plan der Folgephasen klären", "STACK ZUR02 Beringen"),
    ("Oktober", "16.10.2026", "IST-Termin und Lastbank-Bedarf mit Green und Implenia klären", "Green Zürich West 4 Lupfig"),
    ("Oktober", "23.10.2026", "NEA-Lasttest Umzug Jan. 2027 und Rückbau-Baustrom offerieren", "Kantonsspital Aarau «Dreiklang»"),
    ("Oktober", "23.10.2026", "OK kontaktieren, Bedarf abfragen (Unterlagen Französisch)", "FIS Ski-WM Crans-Montana 2027"),
    ("Oktober", "30.10.2026", "Arlesheim und Genf als Paket anbieten", "NorthC Arlesheim (uptownBasel) / NorthC Genf «The Hive»"),
    ("November", "13.11.2026", "Rahmengespräch Einkauf Gruppe", "Burkhalter Gruppe (Rahmen)"),
    ("November", "13.11.2026", "Rahmengespräch Einkauf VINCI Energies CH", "ETAVIS / VINCI Energies (Rahmen)"),
    ("November", "20.11.2026", "Rahmengespräch Einkauf und FM-Leitung", "Equans Switzerland (Rahmen)"),
    ("November", "20.11.2026", "Offerte abgeben, Aufbau startet im Dezember", "WEF Annual Meeting 2027"),
    ("November", "27.11.2026", "GU/Elektro über simap und Baugesuch ermitteln, Baustrom offerieren", "Digital Realty ZUR4 Glattbrugg"),
    ("Dezember", "04.12.2026", "MiT-Mietsätze im Blatt «Annahmen» Spalte E eintragen", "alle"),
    ("Dezember", "11.12.2026", "Kundenstatus aus CRM für alle Top-Player eintragen", "alle"),
    ("Dezember", "18.12.2026", "Backup-Rahmen mit Baustellenleitung besprechen", "2. Gotthardröhre / Sisikoner Tunnel (Neue Axenstrasse)"),
    ("Januar", "15.01.2027", "Review im Team, Pipeline neu rechnen, Prio anpassen", "alle"),
    ("Januar", "22.01.2027", "Beziehung aufbauen, RZ 2028 aufgleisen", "Vantage ZRH3 Volketswil"),
]

GLOSSAR = [
    ("BESS", "Battery Energy Storage System, Batteriespeicher"),
    ("NEA", "Netzersatzanlage (Notstromaggregat)"),
    ("USV", "Unterbrechungsfreie Stromversorgung"),
    ("IST / L1-L5", "Integrated Systems Test, RZ-Gesamttest = Level 5"),
    ("kVA / MVA", "Scheinleistung (Nennleistung Generator)"),
    ("kW / MW", "Wirkleistung; bei cos phi 0,8: 1 MVA ≈ 0,8 MW"),
    ("IT-MW", "Elektrische Leistung der Server im RZ"),
    ("UW / GIS", "Unterwerk / gasisolierte Schaltanlage"),
    ("HS / MS / NS", "Hoch-, Mittel-, Niederspannung"),
    ("HVO", "Hydriertes Pflanzenöl, erneuerbarer Diesel"),
    ("TBM / BSA", "Tunnelbohrmaschine / Tunnel-Sicherheitstechnik"),
    ("RZ", "Rechenzentrum"),
    ("GU / TU / ARGE", "General-, Totalunternehmer / Arbeitsgemeinschaft"),
    ("IBN / PM", "Inbetriebnahme / Projektmanagement"),
    ("IVöB / simap", "Beschaffungsrecht / Ausschreibungsportal"),
    ("EMEA", "Europa, Nahost, Afrika: zentraler Einkauf"),
    ("GMP", "Good Manufacturing Practice (Pharma-Regeln)"),
    ("ASTRA / SBB", "Bundesamt für Strassen / Schweizerische Bundesbahnen"),
    ("EKZ / ewz / CKW / IWB", "Stromversorger Kt. Zürich, Stadt Zürich, Zentralschweiz, Basel"),
    ("KWO / KSA / USZ / KSSG", "Kraftwerke Oberhasli; Spitäler Aarau, Zürich, St.Gallen"),
    ("WEF / FIS / ESAF", "World Economic Forum / Ski-Weltverband / Schwingfest"),
    ("CRM / FX", "Kundendatenbank / Wechselkurs"),
]
